// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Deno from "../bindings/Deno.res.js";

let state = {
  connected: false,
  projectPath: undefined
};

async function connect() {
  try {
    let result = await $$Deno.Command.run("bb", ["--version"], undefined);
    state.connected = result.success;
    return result.success;
  } catch (exn) {
    state.connected = false;
    return false;
  }
}

async function disconnect() {
  state.connected = false;
}

function isConnected() {
  return state.connected;
}

function makeSchema(props, required) {
  let schema = {};
  schema["type"] = "object";
  schema["properties"] = props;
  if (required.length !== 0) {
    schema["required"] = required.map(prim => prim);
  }
  return schema;
}

function makeProp(typeName, desc) {
  return Object.fromEntries([
    [
      "type",
      typeName
    ],
    [
      "description",
      desc
    ]
  ]);
}

let props = {};

let props$1 = {};

let props$2 = {};

let props$3 = {};

let tools = [
  {
    name: "bb_run",
    description: "Run a Babashka script",
    inputSchema: (props["script"] = makeProp("string", "Script file to run"), props["path"] = makeProp("string", "Working directory"), props["args"] = makeProp("string", "Arguments to pass"), makeSchema(props, ["script"]))
  },
  {
    name: "bb_tasks",
    description: "List available bb.edn tasks",
    inputSchema: (props$1["path"] = makeProp("string", "Path to project root"), makeSchema(props$1, []))
  },
  {
    name: "bb_task",
    description: "Run a bb.edn task",
    inputSchema: (props$2["task"] = makeProp("string", "Task name"), props$2["path"] = makeProp("string", "Path to project root"), makeSchema(props$2, ["task"]))
  },
  {
    name: "bb_nrepl",
    description: "Start nREPL server",
    inputSchema: (props$3["port"] = makeProp("number", "nREPL port"), props$3["path"] = makeProp("string", "Working directory"), makeSchema(props$3, []))
  },
  {
    name: "bb_version",
    description: "Get Babashka version",
    inputSchema: makeSchema({}, [])
  }
];

async function executeRun(script, path, args) {
  let cmdArgs = [script];
  let cmdArgs$1 = args !== undefined ? cmdArgs.concat([args]) : cmdArgs;
  return await $$Deno.Command.run("bb", cmdArgs$1, path);
}

async function executeTasks(path) {
  return await $$Deno.Command.run("bb", ["tasks"], path);
}

async function executeTask(task, path) {
  return await $$Deno.Command.run("bb", [task], path);
}

async function executeNrepl(port, path) {
  let args = ["nrepl-server"];
  let args$1 = port !== undefined ? args.concat([port.toString()]) : args;
  return await $$Deno.Command.run("bb", args$1, path);
}

async function executeVersion() {
  return await $$Deno.Command.run("bb", ["--version"], undefined);
}

let name = "Babashka";

let language = "Clojure";

let description = "Fast native Clojure scripting runtime for static site tasks";

export {
  name,
  language,
  description,
  state,
  connect,
  disconnect,
  isConnected,
  makeSchema,
  makeProp,
  tools,
  executeRun,
  executeTasks,
  executeTask,
  executeNrepl,
  executeVersion,
}
/* tools Not a pure module */
