// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Deno from "../bindings/Deno.res.js";

let state = {
  connected: false,
  projectPath: undefined
};

async function connect() {
  try {
    let result = await $$Deno.Command.run("cobalt", ["--version"], undefined);
    state.connected = result.success;
    return result.success;
  } catch (exn) {
    state.connected = false;
    return false;
  }
}

async function disconnect() {
  state.connected = false;
}

function isConnected() {
  return state.connected;
}

function makeSchema(props, required) {
  let schema = {};
  schema["type"] = "object";
  schema["properties"] = props;
  if (required.length !== 0) {
    schema["required"] = required.map(prim => prim);
  }
  return schema;
}

function makeProp(typeName, desc) {
  return Object.fromEntries([
    [
      "type",
      typeName
    ],
    [
      "description",
      desc
    ]
  ]);
}

let props = {};

let props$1 = {};

let props$2 = {};

let props$3 = {};

let props$4 = {};

let props$5 = {};

let tools = [
  {
    name: "cobalt_init",
    description: "Initialize a new Cobalt site",
    inputSchema: (props["path"] = makeProp("string", "Path for the new site"), makeSchema(props, []))
  },
  {
    name: "cobalt_build",
    description: "Build the Cobalt site",
    inputSchema: (props$1["path"] = makeProp("string", "Path to site root"), props$1["destination"] = makeProp("string", "Output directory"), props$1["drafts"] = makeProp("boolean", "Include drafts"), makeSchema(props$1, []))
  },
  {
    name: "cobalt_serve",
    description: "Start Cobalt development server",
    inputSchema: (props$2["path"] = makeProp("string", "Path to site root"), props$2["port"] = makeProp("number", "Port number"), props$2["host"] = makeProp("string", "Host to bind to"), props$2["drafts"] = makeProp("boolean", "Include drafts"), makeSchema(props$2, []))
  },
  {
    name: "cobalt_watch",
    description: "Watch for changes and rebuild",
    inputSchema: (props$3["path"] = makeProp("string", "Path to site root"), makeSchema(props$3, []))
  },
  {
    name: "cobalt_clean",
    description: "Clean the build directory",
    inputSchema: (props$4["path"] = makeProp("string", "Path to site root"), makeSchema(props$4, []))
  },
  {
    name: "cobalt_new",
    description: "Create a new post",
    inputSchema: (props$5["path"] = makeProp("string", "Path to site root"), props$5["title"] = makeProp("string", "Post title"), makeSchema(props$5, ["title"]))
  },
  {
    name: "cobalt_version",
    description: "Get Cobalt version",
    inputSchema: makeSchema({}, [])
  }
];

async function executeInit(path) {
  let args = ["init"];
  let args$1 = path !== undefined ? args.concat([path]) : args;
  return await $$Deno.Command.run("cobalt", args$1, undefined);
}

async function executeBuild(path, destination, drafts) {
  let args = ["build"];
  let args$1 = destination !== undefined ? args.concat([
      "--destination",
      destination
    ]) : args;
  let args$2 = drafts !== undefined && drafts ? args$1.concat(["--drafts"]) : args$1;
  return await $$Deno.Command.run("cobalt", args$2, path);
}

async function executeServe(path, port, host, drafts) {
  let args = ["serve"];
  let args$1 = port !== undefined ? args.concat([
      "--port",
      port.toString()
    ]) : args;
  let args$2 = host !== undefined ? args$1.concat([
      "--host",
      host
    ]) : args$1;
  let args$3 = drafts !== undefined && drafts ? args$2.concat(["--drafts"]) : args$2;
  return await $$Deno.Command.run("cobalt", args$3, path);
}

async function executeWatch(path) {
  return await $$Deno.Command.run("cobalt", ["watch"], path);
}

async function executeClean(path) {
  return await $$Deno.Command.run("cobalt", ["clean"], path);
}

async function executeNew(path, title) {
  return await $$Deno.Command.run("cobalt", [
    "new",
    title
  ], path);
}

async function executeVersion() {
  return await $$Deno.Command.run("cobalt", ["--version"], undefined);
}

let name = "Cobalt";

let language = "Rust";

let description = "Straightforward static site generator written in Rust";

export {
  name,
  language,
  description,
  state,
  connect,
  disconnect,
  isConnected,
  makeSchema,
  makeProp,
  tools,
  executeInit,
  executeBuild,
  executeServe,
  executeWatch,
  executeClean,
  executeNew,
  executeVersion,
}
/* tools Not a pure module */
