// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Deno from "../bindings/Deno.res.js";

let state = {
  connected: false,
  projectPath: undefined
};

async function connect() {
  try {
    let result = await $$Deno.Command.run("sbcl", ["--version"], undefined);
    state.connected = result.success;
    return result.success;
  } catch (exn) {
    state.connected = false;
    return false;
  }
}

async function disconnect() {
  state.connected = false;
}

function isConnected() {
  return state.connected;
}

function makeSchema(props, required) {
  let schema = {};
  schema["type"] = "object";
  schema["properties"] = props;
  if (required.length !== 0) {
    schema["required"] = required.map(prim => prim);
  }
  return schema;
}

function makeProp(typeName, desc) {
  return Object.fromEntries([
    [
      "type",
      typeName
    ],
    [
      "description",
      desc
    ]
  ]);
}

let props = {};

let props$1 = {};

let props$2 = {};

let props$3 = {};

let tools = [
  {
    name: "coleslaw_init",
    description: "Initialize a new Coleslaw blog",
    inputSchema: (props["path"] = makeProp("string", "Path for the new blog"), makeSchema(props, ["path"]))
  },
  {
    name: "coleslaw_build",
    description: "Build the Coleslaw blog",
    inputSchema: (props$1["path"] = makeProp("string", "Path to blog root"), makeSchema(props$1, []))
  },
  {
    name: "coleslaw_preview",
    description: "Preview the blog locally",
    inputSchema: (props$2["path"] = makeProp("string", "Path to blog root"), props$2["port"] = makeProp("number", "Port number"), makeSchema(props$2, []))
  },
  {
    name: "coleslaw_new_post",
    description: "Create a new blog post",
    inputSchema: (props$3["path"] = makeProp("string", "Path to blog root"), props$3["title"] = makeProp("string", "Post title"), makeSchema(props$3, ["title"]))
  },
  {
    name: "coleslaw_version",
    description: "Get SBCL version",
    inputSchema: makeSchema({}, [])
  }
];

async function executeInit(path) {
  return await $$Deno.Command.run("sbcl", [
    "--eval",
    "(ql:quickload :coleslaw)",
    "--eval",
    `(coleslaw:setup "` + path + `")`,
    "--quit"
  ], undefined);
}

async function executeBuild(path) {
  let evalArg = path !== undefined ? `(coleslaw:main "` + path + `")` : "(coleslaw:main)";
  return await $$Deno.Command.run("sbcl", [
    "--eval",
    "(ql:quickload :coleslaw)",
    "--eval",
    evalArg,
    "--quit"
  ], undefined);
}

async function executePreview(path, port) {
  let portStr = port !== undefined ? port.toString() : "8000";
  let evalArg = path !== undefined ? `(coleslaw:preview "` + path + `" :port ` + portStr + `)` : `(coleslaw:preview :port ` + portStr + `)`;
  return await $$Deno.Command.run("sbcl", [
    "--eval",
    "(ql:quickload :coleslaw)",
    "--eval",
    evalArg
  ], undefined);
}

async function executeNewPost(path, title) {
  let evalArg = path !== undefined ? `(coleslaw:new-post "` + path + `" :title "` + title + `")` : `(coleslaw:new-post :title "` + title + `")`;
  return await $$Deno.Command.run("sbcl", [
    "--eval",
    "(ql:quickload :coleslaw)",
    "--eval",
    evalArg,
    "--quit"
  ], undefined);
}

async function executeVersion() {
  return await $$Deno.Command.run("sbcl", ["--version"], undefined);
}

let name = "Coleslaw";

let language = "Common Lisp";

let description = "Flexible static blog generator written in Common Lisp";

export {
  name,
  language,
  description,
  state,
  connect,
  disconnect,
  isConnected,
  makeSchema,
  makeProp,
  tools,
  executeInit,
  executeBuild,
  executePreview,
  executeNewPost,
  executeVersion,
}
/* tools Not a pure module */
