// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Deno from "../bindings/Deno.res.js";

let state = {
  connected: false,
  projectPath: undefined
};

async function connect() {
  try {
    let result = await $$Deno.Command.run("corral", ["version"], undefined);
    state.connected = result.success;
    return result.success;
  } catch (exn) {
    state.connected = false;
    return false;
  }
}

async function disconnect() {
  state.connected = false;
}

function isConnected() {
  return state.connected;
}

function makeSchema(props, required) {
  let schema = {};
  schema["type"] = "object";
  schema["properties"] = props;
  if (required.length !== 0) {
    schema["required"] = required.map(prim => prim);
  }
  return schema;
}

function makeProp(typeName, desc) {
  return Object.fromEntries([
    [
      "type",
      typeName
    ],
    [
      "description",
      desc
    ]
  ]);
}

let props = {};

let props$1 = {};

let props$2 = {};

let props$3 = {};

let props$4 = {};

let props$5 = {};

let tools = [
  {
    name: "corral_init",
    description: "Initialize a new Pony site project with Corral package manager",
    inputSchema: (props["path"] = makeProp("string", "Path for the new site"), props["template"] = makeProp("string", "Template to use (blog, docs, portfolio)"), makeSchema(props, ["path"]))
  },
  {
    name: "corral_build",
    description: "Build the Pony static site",
    inputSchema: (props$1["path"] = makeProp("string", "Path to site root"), props$1["outputDir"] = makeProp("string", "Output directory for built site"), props$1["release"] = makeProp("boolean", "Build in release mode with optimizations"), makeSchema(props$1, []))
  },
  {
    name: "corral_serve",
    description: "Start Pony development server with live reload",
    inputSchema: (props$2["path"] = makeProp("string", "Path to site root"), props$2["port"] = makeProp("number", "Port number (default: 8080)"), props$2["host"] = makeProp("string", "Host to bind to (default: 127.0.0.1)"), makeSchema(props$2, []))
  },
  {
    name: "corral_clean",
    description: "Clean build artifacts from the Pony site",
    inputSchema: (props$3["path"] = makeProp("string", "Path to site root"), makeSchema(props$3, []))
  },
  {
    name: "corral_version",
    description: "Get Corral and Pony version information",
    inputSchema: makeSchema({}, [])
  },
  {
    name: "corral_new_post",
    description: "Create a new blog post or content page",
    inputSchema: (props$4["path"] = makeProp("string", "Path to site root"), props$4["title"] = makeProp("string", "Title of the new post"), props$4["draft"] = makeProp("boolean", "Mark as draft"), makeSchema(props$4, ["title"]))
  },
  {
    name: "corral_check",
    description: "Check and validate the site configuration and content",
    inputSchema: (props$5["path"] = makeProp("string", "Path to site root"), makeSchema(props$5, []))
  }
];

async function executeInit(path, template) {
  let args = [
    "init",
    path
  ];
  let args$1 = template !== undefined ? args.concat([
      "--template",
      template
    ]) : args;
  return await $$Deno.Command.run("corral", args$1, undefined);
}

async function executeBuild(path, outputDir, release) {
  let args = ["build"];
  let args$1 = outputDir !== undefined ? args.concat([
      "--output",
      outputDir
    ]) : args;
  let args$2 = release !== undefined && release ? args$1.concat(["--release"]) : args$1;
  return await $$Deno.Command.run("corral", args$2, path);
}

async function executeServe(path, port, host) {
  let args = ["serve"];
  let args$1 = port !== undefined ? args.concat([
      "--port",
      port.toString()
    ]) : args;
  let args$2 = host !== undefined ? args$1.concat([
      "--host",
      host
    ]) : args$1;
  return await $$Deno.Command.run("corral", args$2, path);
}

async function executeClean(path) {
  return await $$Deno.Command.run("corral", ["clean"], path);
}

async function executeVersion() {
  return await $$Deno.Command.run("corral", ["version"], undefined);
}

async function executeNewPost(path, title, draft) {
  let args = [
    "new",
    "post",
    title
  ];
  let args$1 = draft !== undefined && draft ? args.concat(["--draft"]) : args;
  return await $$Deno.Command.run("corral", args$1, path);
}

async function executeCheck(path) {
  return await $$Deno.Command.run("corral", ["check"], path);
}

let name = "Corral";

let language = "Pony";

let description = "Static site generator written in Pony with capability-based security and actor-model concurrency";

export {
  name,
  language,
  description,
  state,
  connect,
  disconnect,
  isConnected,
  makeSchema,
  makeProp,
  tools,
  executeInit,
  executeBuild,
  executeServe,
  executeClean,
  executeVersion,
  executeNewPost,
  executeCheck,
}
/* tools Not a pure module */
