// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Deno from "../bindings/Deno.res.js";

let state = {
  connected: false,
  projectPath: undefined
};

async function connect() {
  try {
    let result = await $$Deno.Command.run("lein", ["version"], undefined);
    state.connected = result.success;
    return result.success;
  } catch (exn) {
    state.connected = false;
    return false;
  }
}

async function disconnect() {
  state.connected = false;
}

function isConnected() {
  return state.connected;
}

function makeSchema(props, required) {
  let schema = {};
  schema["type"] = "object";
  schema["properties"] = props;
  if (required.length !== 0) {
    schema["required"] = required.map(prim => prim);
  }
  return schema;
}

function makeProp(typeName, desc) {
  return Object.fromEntries([
    [
      "type",
      typeName
    ],
    [
      "description",
      desc
    ]
  ]);
}

let props = {};

let props$1 = {};

let props$2 = {};

let props$3 = {};

let tools = [
  {
    name: "cryogen_new",
    description: "Create a new Cryogen site",
    inputSchema: (props["name"] = makeProp("string", "Project name"), props["path"] = makeProp("string", "Path for the project"), makeSchema(props, ["name"]))
  },
  {
    name: "cryogen_build",
    description: "Build the Cryogen site",
    inputSchema: (props$1["path"] = makeProp("string", "Path to project root"), makeSchema(props$1, []))
  },
  {
    name: "cryogen_serve",
    description: "Start Cryogen development server",
    inputSchema: (props$2["path"] = makeProp("string", "Path to project root"), props$2["port"] = makeProp("number", "Port number (default: 3000)"), makeSchema(props$2, []))
  },
  {
    name: "cryogen_new_post",
    description: "Create a new blog post",
    inputSchema: (props$3["path"] = makeProp("string", "Path to project root"), props$3["title"] = makeProp("string", "Post title"), makeSchema(props$3, ["title"]))
  },
  {
    name: "cryogen_version",
    description: "Get Leiningen version",
    inputSchema: makeSchema({}, [])
  }
];

async function executeNew(name, path) {
  return await $$Deno.Command.run("lein", [
    "new",
    "cryogen",
    name
  ], path);
}

async function executeBuild(path) {
  return await $$Deno.Command.run("lein", ["run"], path);
}

async function executeServe(path, port) {
  let args = [
    "ring",
    "server"
  ];
  let args$1 = port !== undefined ? args.concat([port.toString()]) : args;
  return await $$Deno.Command.run("lein", args$1, path);
}

async function executeNewPost(path, title) {
  return await $$Deno.Command.run("lein", [
    "run",
    "-m",
    "cryogen.core/new-post!",
    title
  ], path);
}

async function executeVersion() {
  return await $$Deno.Command.run("lein", ["version"], undefined);
}

let name = "Cryogen";

let language = "Clojure";

let description = "Simple static site generator using Clojure and Leiningen";

export {
  name,
  language,
  description,
  state,
  connect,
  disconnect,
  isConnected,
  makeSchema,
  makeProp,
  tools,
  executeNew,
  executeBuild,
  executeServe,
  executeNewPost,
  executeVersion,
}
/* tools Not a pure module */
