// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Deno from "../bindings/Deno.res.js";

let state = {
  connected: false,
  projectPath: undefined
};

async function connect() {
  try {
    let result = await $$Deno.Command.run("julia", ["--version"], undefined);
    state.connected = result.success;
    return result.success;
  } catch (exn) {
    state.connected = false;
    return false;
  }
}

async function disconnect() {
  state.connected = false;
}

function isConnected() {
  return state.connected;
}

function makeSchema(props, required) {
  let schema = {};
  schema["type"] = "object";
  schema["properties"] = props;
  if (required.length !== 0) {
    schema["required"] = required.map(prim => prim);
  }
  return schema;
}

function makeProp(typeName, desc) {
  return Object.fromEntries([
    [
      "type",
      typeName
    ],
    [
      "description",
      desc
    ]
  ]);
}

let props = {};

let props$1 = {};

let props$2 = {};

let props$3 = {};

let tools = [
  {
    name: "documenter_init",
    description: "Initialize Documenter for a Julia package",
    inputSchema: (props["path"] = makeProp("string", "Path to Julia package"), makeSchema(props, ["path"]))
  },
  {
    name: "documenter_build",
    description: "Build documentation",
    inputSchema: (props$1["path"] = makeProp("string", "Path to docs/ directory"), props$1["strict"] = makeProp("boolean", "Strict mode (fail on warnings)"), makeSchema(props$1, []))
  },
  {
    name: "documenter_serve",
    description: "Serve documentation locally",
    inputSchema: (props$2["path"] = makeProp("string", "Path to docs/build/ directory"), props$2["port"] = makeProp("number", "Port number"), makeSchema(props$2, []))
  },
  {
    name: "documenter_deploy",
    description: "Deploy documentation to GitHub Pages",
    inputSchema: (props$3["path"] = makeProp("string", "Path to docs/ directory"), makeSchema(props$3, []))
  },
  {
    name: "documenter_version",
    description: "Get Documenter version",
    inputSchema: makeSchema({}, [])
  }
];

async function executeInit(path) {
  return await $$Deno.Command.run("julia", [
    "-e",
    `using DocumenterTools; DocumenterTools.generate("` + path + `")`
  ], undefined);
}

async function executeBuild(path, _strict) {
  let docsPath = path !== undefined ? path : "docs";
  return await $$Deno.Command.run("julia", [
    "--project=" + docsPath,
    docsPath + "/make.jl"
  ], undefined);
}

async function executeServe(path, port) {
  let portArg = port !== undefined ? port.toString() : "8000";
  let buildPath = path !== undefined ? path : "docs/build";
  return await $$Deno.Command.run("julia", [
    "-e",
    `using LiveServer; serve(dir="` + buildPath + `", port=` + portArg + `)`
  ], undefined);
}

async function executeDeploy(path) {
  let docsPath = path !== undefined ? path : "docs";
  return await $$Deno.Command.run("julia", [
    "--project=" + docsPath,
    docsPath + "/make.jl",
    "--deploy"
  ], undefined);
}

async function executeVersion() {
  return await $$Deno.Command.run("julia", [
    "-e",
    "using Documenter; println(Documenter.DOCUMENTER_VERSION)"
  ], undefined);
}

let name = "Documenter";

let language = "Julia";

let description = "Documentation generator for Julia packages";

export {
  name,
  language,
  description,
  state,
  connect,
  disconnect,
  isConnected,
  makeSchema,
  makeProp,
  tools,
  executeInit,
  executeBuild,
  executeServe,
  executeDeploy,
  executeVersion,
}
/* tools Not a pure module */
