// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Deno from "../bindings/Deno.res.js";

let state = {
  connected: false,
  projectPath: undefined
};

async function connect() {
  try {
    let result = await $$Deno.Command.run("ema", ["--version"], undefined);
    state.connected = result.success;
    return result.success;
  } catch (exn) {
    state.connected = false;
    return false;
  }
}

async function disconnect() {
  state.connected = false;
}

function isConnected() {
  return state.connected;
}

function makeSchema(props, required) {
  let schema = {};
  schema["type"] = "object";
  schema["properties"] = props;
  if (required.length !== 0) {
    schema["required"] = required.map(prim => prim);
  }
  return schema;
}

function makeProp(typeName, desc) {
  return Object.fromEntries([
    [
      "type",
      typeName
    ],
    [
      "description",
      desc
    ]
  ]);
}

let props = {};

let props$1 = {};

let props$2 = {};

let tools = [
  {
    name: "ema_init",
    description: "Initialize a new Ema project",
    inputSchema: (props["name"] = makeProp("string", "Project name"), props["path"] = makeProp("string", "Path for the project"), makeSchema(props, ["name"]))
  },
  {
    name: "ema_build",
    description: "Build the Ema site (generate static files)",
    inputSchema: (props$1["path"] = makeProp("string", "Path to project root"), props$1["output"] = makeProp("string", "Output directory"), makeSchema(props$1, []))
  },
  {
    name: "ema_run",
    description: "Start Ema development server with hot reload",
    inputSchema: (props$2["path"] = makeProp("string", "Path to project root"), props$2["port"] = makeProp("number", "Port number"), props$2["host"] = makeProp("string", "Host to bind to"), makeSchema(props$2, []))
  },
  {
    name: "ema_version",
    description: "Get Ema version",
    inputSchema: makeSchema({}, [])
  }
];

async function executeInit(name, path) {
  return await $$Deno.Command.run("nix", [
    "flake",
    "init",
    "-t",
    "github:srid/ema#template",
    name
  ], path);
}

async function executeBuild(path, output) {
  let args = ["gen"];
  let args$1 = output !== undefined ? args.concat([
      "--dest",
      output
    ]) : args;
  return await $$Deno.Command.run("ema", args$1, path);
}

async function executeRun(path, port, host) {
  let args = ["run"];
  let args$1 = port !== undefined ? args.concat([
      "--port",
      port.toString()
    ]) : args;
  let args$2 = host !== undefined ? args$1.concat([
      "--host",
      host
    ]) : args$1;
  return await $$Deno.Command.run("ema", args$2, path);
}

async function executeVersion() {
  return await $$Deno.Command.run("ema", ["--version"], undefined);
}

let name = "Ema";

let language = "Haskell";

let description = "Static site generator in Haskell with hot reload and Nix support";

export {
  name,
  language,
  description,
  state,
  connect,
  disconnect,
  isConnected,
  makeSchema,
  makeProp,
  tools,
  executeInit,
  executeBuild,
  executeRun,
  executeVersion,
}
/* tools Not a pure module */
