// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Deno from "../bindings/Deno.res.js";

let state = {
  connected: false,
  projectPath: undefined
};

async function connect() {
  try {
    let result = await $$Deno.Command.run("fornax", ["version"], undefined);
    state.connected = result.success;
    return result.success;
  } catch (exn) {
    state.connected = false;
    return false;
  }
}

async function disconnect() {
  state.connected = false;
}

function isConnected() {
  return state.connected;
}

function makeSchema(props, required) {
  let schema = {};
  schema["type"] = "object";
  schema["properties"] = props;
  if (required.length !== 0) {
    schema["required"] = required.map(prim => prim);
  }
  return schema;
}

function makeProp(typeName, desc) {
  return Object.fromEntries([
    [
      "type",
      typeName
    ],
    [
      "description",
      desc
    ]
  ]);
}

let props = {};

let props$1 = {};

let props$2 = {};

let props$3 = {};

let tools = [
  {
    name: "fornax_new",
    description: "Create a new Fornax project",
    inputSchema: (props["path"] = makeProp("string", "Path for the new project"), makeSchema(props, []))
  },
  {
    name: "fornax_build",
    description: "Build the Fornax site",
    inputSchema: (props$1["path"] = makeProp("string", "Path to project root"), makeSchema(props$1, []))
  },
  {
    name: "fornax_watch",
    description: "Start Fornax watch server",
    inputSchema: (props$2["path"] = makeProp("string", "Path to project root"), props$2["port"] = makeProp("number", "Port number (default: 8080)"), makeSchema(props$2, []))
  },
  {
    name: "fornax_clean",
    description: "Clean build output",
    inputSchema: (props$3["path"] = makeProp("string", "Path to project root"), makeSchema(props$3, []))
  },
  {
    name: "fornax_version",
    description: "Get Fornax version",
    inputSchema: makeSchema({}, [])
  }
];

async function executeNew(path) {
  let args = ["new"];
  let args$1 = path !== undefined ? args.concat([path]) : args;
  return await $$Deno.Command.run("fornax", args$1, undefined);
}

async function executeBuild(path) {
  return await $$Deno.Command.run("fornax", ["build"], path);
}

async function executeWatch(path, port) {
  let args = ["watch"];
  let args$1 = port !== undefined ? args.concat([
      "--port",
      port.toString()
    ]) : args;
  return await $$Deno.Command.run("fornax", args$1, path);
}

async function executeClean(path) {
  return await $$Deno.Command.run("fornax", ["clean"], path);
}

async function executeVersion() {
  return await $$Deno.Command.run("fornax", ["version"], undefined);
}

let name = "Fornax";

let language = "F#";

let description = "Static site generator using type-safe F# DSL";

export {
  name,
  language,
  description,
  state,
  connect,
  disconnect,
  isConnected,
  makeSchema,
  makeProp,
  tools,
  executeNew,
  executeBuild,
  executeWatch,
  executeClean,
  executeVersion,
}
/* tools Not a pure module */
