// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Deno from "../bindings/Deno.res.js";

let state = {
  connected: false,
  projectPath: undefined
};

async function connect() {
  try {
    let result = await $$Deno.Command.run("julia", ["--version"], undefined);
    state.connected = result.success;
    return result.success;
  } catch (exn) {
    state.connected = false;
    return false;
  }
}

async function disconnect() {
  state.connected = false;
}

function isConnected() {
  return state.connected;
}

function makeSchema(props, required) {
  let schema = {};
  schema["type"] = "object";
  schema["properties"] = props;
  if (required.length !== 0) {
    schema["required"] = required.map(prim => prim);
  }
  return schema;
}

function makeProp(typeName, desc) {
  return Object.fromEntries([
    [
      "type",
      typeName
    ],
    [
      "description",
      desc
    ]
  ]);
}

let props = {};

let props$1 = {};

let props$2 = {};

let props$3 = {};

let tools = [
  {
    name: "franklin_new",
    description: "Create a new Franklin site",
    inputSchema: (props["path"] = makeProp("string", "Path for the new site"), props["template"] = makeProp("string", "Template name"), makeSchema(props, ["path"]))
  },
  {
    name: "franklin_serve",
    description: "Start Franklin development server",
    inputSchema: (props$1["path"] = makeProp("string", "Path to site root"), props$1["port"] = makeProp("number", "Port number (default: 8000)"), props$1["host"] = makeProp("string", "Host to bind to"), props$1["clear"] = makeProp("boolean", "Clear cache before serving"), makeSchema(props$1, []))
  },
  {
    name: "franklin_optimize",
    description: "Optimize the site for production",
    inputSchema: (props$2["path"] = makeProp("string", "Path to site root"), props$2["minify"] = makeProp("boolean", "Minify HTML/CSS/JS"), props$2["prerender"] = makeProp("boolean", "Pre-render pages"), makeSchema(props$2, []))
  },
  {
    name: "franklin_publish",
    description: "Publish site to GitHub Pages",
    inputSchema: (props$3["path"] = makeProp("string", "Path to site root"), makeSchema(props$3, []))
  },
  {
    name: "franklin_version",
    description: "Get Julia/Franklin version",
    inputSchema: makeSchema({}, [])
  }
];

async function executeNew(path, template) {
  let templateArg = template !== undefined ? `, template="` + template + `"` : "";
  return await $$Deno.Command.run("julia", [
    "-e",
    `using Franklin; newsite("` + path + `"` + templateArg + `)`
  ], undefined);
}

async function executeServe(path, port, host, clear) {
  let portArg = port !== undefined ? `, port=` + port.toString() : "";
  let hostArg = host !== undefined ? `, host="` + host + `"` : "";
  let clearArg = clear !== undefined && clear ? ", clear=true" : "";
  let dir = path !== undefined ? `cd("` + path + `"); ` : "";
  return await $$Deno.Command.run("julia", [
    "-e",
    `using Franklin; ` + dir + `serve(` + portArg + hostArg + clearArg + `)`
  ], undefined);
}

async function executeOptimize(path, minify, prerender) {
  let minifyArg = minify !== undefined && minify ? ", minify=true" : "";
  let prerenderArg = prerender !== undefined && prerender ? ", prerender=true" : "";
  let dir = path !== undefined ? `cd("` + path + `"); ` : "";
  return await $$Deno.Command.run("julia", [
    "-e",
    `using Franklin; ` + dir + `optimize(` + minifyArg + prerenderArg + `)`
  ], undefined);
}

async function executePublish(path) {
  let dir = path !== undefined ? `cd("` + path + `"); ` : "";
  return await $$Deno.Command.run("julia", [
    "-e",
    `using Franklin; ` + dir + `publish()`
  ], undefined);
}

async function executeVersion() {
  return await $$Deno.Command.run("julia", [
    "-e",
    "using Franklin; println(Franklin.FRANKLIN_VERSION)"
  ], undefined);
}

let name = "Franklin";

let language = "Julia";

let description = "Static site generator for technical blogging in Julia";

export {
  name,
  language,
  description,
  state,
  connect,
  disconnect,
  isConnected,
  makeSchema,
  makeProp,
  tools,
  executeNew,
  executeServe,
  executeOptimize,
  executePublish,
  executeVersion,
}
/* tools Not a pure module */
