// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Deno from "../bindings/Deno.res.js";

let state = {
  connected: false,
  projectPath: undefined
};

async function connect() {
  try {
    let result = await $$Deno.Command.run("raco", [
      "frog",
      "--help"
    ], undefined);
    state.connected = result.success;
    return result.success;
  } catch (exn) {
    state.connected = false;
    return false;
  }
}

async function disconnect() {
  state.connected = false;
}

function isConnected() {
  return state.connected;
}

function makeSchema(props, required) {
  let schema = {};
  schema["type"] = "object";
  schema["properties"] = props;
  if (required.length !== 0) {
    schema["required"] = required.map(prim => prim);
  }
  return schema;
}

function makeProp(typeName, desc) {
  return Object.fromEntries([
    [
      "type",
      typeName
    ],
    [
      "description",
      desc
    ]
  ]);
}

let props = {};

let props$1 = {};

let props$2 = {};

let props$3 = {};

let props$4 = {};

let tools = [
  {
    name: "frog_init",
    description: "Initialize a new Frog blog",
    inputSchema: (props["path"] = makeProp("string", "Path for the new blog"), makeSchema(props, []))
  },
  {
    name: "frog_build",
    description: "Build the Frog blog",
    inputSchema: (props$1["path"] = makeProp("string", "Path to blog root"), makeSchema(props$1, []))
  },
  {
    name: "frog_preview",
    description: "Start Frog preview server",
    inputSchema: (props$2["path"] = makeProp("string", "Path to blog root"), props$2["port"] = makeProp("number", "Port number (default: 3000)"), makeSchema(props$2, []))
  },
  {
    name: "frog_new",
    description: "Create a new blog post",
    inputSchema: (props$3["path"] = makeProp("string", "Path to blog root"), props$3["title"] = makeProp("string", "Post title"), makeSchema(props$3, ["title"]))
  },
  {
    name: "frog_clean",
    description: "Clean generated files",
    inputSchema: (props$4["path"] = makeProp("string", "Path to blog root"), makeSchema(props$4, []))
  },
  {
    name: "frog_version",
    description: "Get Frog version",
    inputSchema: makeSchema({}, [])
  }
];

async function executeInit(path) {
  return await $$Deno.Command.run("raco", [
    "frog",
    "--init"
  ], path);
}

async function executeBuild(path) {
  return await $$Deno.Command.run("raco", [
    "frog",
    "-b"
  ], path);
}

async function executePreview(path, port) {
  let args = [
    "frog",
    "-p"
  ];
  let args$1 = port !== undefined ? args.concat([
      "--port",
      port.toString()
    ]) : args;
  return await $$Deno.Command.run("raco", args$1, path);
}

async function executeNew(path, title) {
  return await $$Deno.Command.run("raco", [
    "frog",
    "-n",
    title
  ], path);
}

async function executeClean(path) {
  return await $$Deno.Command.run("raco", [
    "frog",
    "--clean"
  ], path);
}

async function executeVersion() {
  return await $$Deno.Command.run("raco", [
    "frog",
    "--version"
  ], undefined);
}

let name = "Frog";

let language = "Racket";

let description = "Static blog generator using Racket with Markdown and Pygments";

export {
  name,
  language,
  description,
  state,
  connect,
  disconnect,
  isConnected,
  makeSchema,
  makeProp,
  tools,
  executeInit,
  executeBuild,
  executePreview,
  executeNew,
  executeClean,
  executeVersion,
}
/* tools Not a pure module */
