// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Deno from "../bindings/Deno.res.js";

let state = {
  connected: false,
  projectPath: undefined
};

async function connect() {
  try {
    let result = await $$Deno.Command.run("stack", ["--version"], undefined);
    state.connected = result.success;
    return result.success;
  } catch (exn) {
    state.connected = false;
    return false;
  }
}

async function disconnect() {
  state.connected = false;
}

function isConnected() {
  return state.connected;
}

function makeSchema(props, required) {
  let schema = {};
  schema["type"] = "object";
  schema["properties"] = props;
  if (required.length !== 0) {
    schema["required"] = required.map(prim => prim);
  }
  return schema;
}

function makeProp(typeName, desc) {
  return Object.fromEntries([
    [
      "type",
      typeName
    ],
    [
      "description",
      desc
    ]
  ]);
}

let props = {};

let props$1 = {};

let props$2 = {};

let props$3 = {};

let props$4 = {};

let props$5 = {};

let props$6 = {};

let tools = [
  {
    name: "hakyll_init",
    description: "Initialize a new Hakyll site (using stack template)",
    inputSchema: (props["name"] = makeProp("string", "Project name"), props["path"] = makeProp("string", "Path for the project"), makeSchema(props, ["name"]))
  },
  {
    name: "hakyll_build",
    description: "Build the Hakyll site",
    inputSchema: (props$1["path"] = makeProp("string", "Path to site root"), makeSchema(props$1, []))
  },
  {
    name: "hakyll_watch",
    description: "Start Hakyll watch server",
    inputSchema: (props$2["path"] = makeProp("string", "Path to site root"), props$2["port"] = makeProp("number", "Port number"), props$2["host"] = makeProp("string", "Host to bind to"), makeSchema(props$2, []))
  },
  {
    name: "hakyll_clean",
    description: "Clean the build cache",
    inputSchema: (props$3["path"] = makeProp("string", "Path to site root"), makeSchema(props$3, []))
  },
  {
    name: "hakyll_rebuild",
    description: "Clean and rebuild the site",
    inputSchema: (props$4["path"] = makeProp("string", "Path to site root"), makeSchema(props$4, []))
  },
  {
    name: "hakyll_check",
    description: "Check for broken links",
    inputSchema: (props$5["path"] = makeProp("string", "Path to site root"), props$5["internal"] = makeProp("boolean", "Check internal links only"), makeSchema(props$5, []))
  },
  {
    name: "hakyll_deploy",
    description: "Deploy the site",
    inputSchema: (props$6["path"] = makeProp("string", "Path to site root"), makeSchema(props$6, []))
  },
  {
    name: "hakyll_version",
    description: "Get Stack/Hakyll version",
    inputSchema: makeSchema({}, [])
  }
];

async function runSiteCommand(args, path) {
  return await $$Deno.Command.run("stack", [
    "exec",
    "site",
    "--"
  ].concat(args), path);
}

async function executeInit(name, path) {
  return await $$Deno.Command.run("stack", [
    "new",
    name,
    "hakyll-template"
  ], path);
}

async function executeBuild(path) {
  return await runSiteCommand(["build"], path);
}

async function executeWatch(path, port, host) {
  let args = ["watch"];
  let args$1 = port !== undefined ? args.concat([
      "--port",
      port.toString()
    ]) : args;
  let args$2 = host !== undefined ? args$1.concat([
      "--host",
      host
    ]) : args$1;
  return await runSiteCommand(args$2, path);
}

async function executeClean(path) {
  return await runSiteCommand(["clean"], path);
}

async function executeRebuild(path) {
  return await runSiteCommand(["rebuild"], path);
}

async function executeCheck(path, internal) {
  let args = ["check"];
  let args$1 = internal !== undefined && internal ? args.concat(["--internal-links"]) : args;
  return await runSiteCommand(args$1, path);
}

async function executeDeploy(path) {
  return await runSiteCommand(["deploy"], path);
}

async function executeVersion() {
  return await $$Deno.Command.run("stack", ["--version"], undefined);
}

let name = "Hakyll";

let language = "Haskell";

let description = "Haskell library for generating static sites with Pandoc support";

export {
  name,
  language,
  description,
  state,
  connect,
  disconnect,
  isConnected,
  makeSchema,
  makeProp,
  tools,
  runSiteCommand,
  executeInit,
  executeBuild,
  executeWatch,
  executeClean,
  executeRebuild,
  executeCheck,
  executeDeploy,
  executeVersion,
}
/* tools Not a pure module */
