// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Deno from "../bindings/Deno.res.js";

let state = {
  connected: false,
  projectPath: undefined
};

async function connect() {
  try {
    let result = await $$Deno.Command.run("laika", ["--version"], undefined);
    state.connected = result.success;
    return result.success;
  } catch (exn) {
    state.connected = false;
    return false;
  }
}

async function disconnect() {
  state.connected = false;
}

function isConnected() {
  return state.connected;
}

function makeSchema(props, required) {
  let schema = {};
  schema["type"] = "object";
  schema["properties"] = props;
  if (required.length !== 0) {
    schema["required"] = required.map(prim => prim);
  }
  return schema;
}

function makeProp(typeName, desc) {
  return Object.fromEntries([
    [
      "type",
      typeName
    ],
    [
      "description",
      desc
    ]
  ]);
}

let props = {};

let props$1 = {};

let props$2 = {};

let tools = [
  {
    name: "laika_transform",
    description: "Transform markup files",
    inputSchema: (props["input"] = makeProp("string", "Input directory or file"), props["output"] = makeProp("string", "Output directory"), props["format"] = makeProp("string", "Output format (html, epub, pdf, ast)"), makeSchema(props, [
      "input",
      "output"
    ]))
  },
  {
    name: "laika_generate",
    description: "Generate a site from markup",
    inputSchema: (props$1["path"] = makeProp("string", "Path to project root"), props$1["output"] = makeProp("string", "Output directory"), makeSchema(props$1, []))
  },
  {
    name: "laika_preview",
    description: "Start preview server",
    inputSchema: (props$2["path"] = makeProp("string", "Path to project root"), props$2["port"] = makeProp("number", "Port number"), makeSchema(props$2, []))
  },
  {
    name: "laika_version",
    description: "Get Laika version",
    inputSchema: makeSchema({}, [])
  }
];

async function executeTransform(input, output, format) {
  let args = [
    "transform",
    input,
    output
  ];
  let args$1 = format !== undefined ? args.concat([
      "--format",
      format
    ]) : args;
  return await $$Deno.Command.run("laika", args$1, undefined);
}

async function executeGenerate(path, output) {
  let args = ["generate"];
  let args$1 = output !== undefined ? args.concat([
      "--output",
      output
    ]) : args;
  return await $$Deno.Command.run("laika", args$1, path);
}

async function executePreview(path, port) {
  let args = ["preview"];
  let args$1 = port !== undefined ? args.concat([
      "--port",
      port.toString()
    ]) : args;
  return await $$Deno.Command.run("laika", args$1, path);
}

async function executeVersion() {
  return await $$Deno.Command.run("laika", ["--version"], undefined);
}

let name = "Laika";

let language = "Scala";

let description = "Customizable text markup transformer and site generator in Scala";

export {
  name,
  language,
  description,
  state,
  connect,
  disconnect,
  isConnected,
  makeSchema,
  makeProp,
  tools,
  executeTransform,
  executeGenerate,
  executePreview,
  executeVersion,
}
/* tools Not a pure module */
