// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Deno from "../bindings/Deno.res.js";

let state = {
  connected: false,
  projectPath: undefined
};

async function connect() {
  try {
    let result = await $$Deno.Command.run("marmot", ["--version"], undefined);
    state.connected = result.success;
    return result.success;
  } catch (exn) {
    state.connected = false;
    return false;
  }
}

async function disconnect() {
  state.connected = false;
}

function isConnected() {
  return state.connected;
}

function makeSchema(props, required) {
  let schema = {};
  schema["type"] = "object";
  schema["properties"] = props;
  if (required.length !== 0) {
    schema["required"] = required.map(prim => prim);
  }
  return schema;
}

function makeProp(typeName, desc) {
  return Object.fromEntries([
    [
      "type",
      typeName
    ],
    [
      "description",
      desc
    ]
  ]);
}

let props = {};

let props$1 = {};

let props$2 = {};

let props$3 = {};

let tools = [
  {
    name: "marmot_init",
    description: "Initialize a new Marmot site",
    inputSchema: (props["path"] = makeProp("string", "Path for the new site"), makeSchema(props, []))
  },
  {
    name: "marmot_build",
    description: "Build the Marmot site",
    inputSchema: (props$1["path"] = makeProp("string", "Path to site root"), props$1["output"] = makeProp("string", "Output directory"), makeSchema(props$1, []))
  },
  {
    name: "marmot_serve",
    description: "Start Marmot development server",
    inputSchema: (props$2["path"] = makeProp("string", "Path to site root"), props$2["port"] = makeProp("number", "Port number"), makeSchema(props$2, []))
  },
  {
    name: "marmot_watch",
    description: "Watch for changes and rebuild",
    inputSchema: (props$3["path"] = makeProp("string", "Path to site root"), makeSchema(props$3, []))
  },
  {
    name: "marmot_version",
    description: "Get Marmot version",
    inputSchema: makeSchema({}, [])
  }
];

async function executeInit(path) {
  let args = ["init"];
  let args$1 = path !== undefined ? args.concat([path]) : args;
  return await $$Deno.Command.run("marmot", args$1, undefined);
}

async function executeBuild(path, output) {
  let args = ["build"];
  let args$1 = output !== undefined ? args.concat([
      "--output",
      output
    ]) : args;
  return await $$Deno.Command.run("marmot", args$1, path);
}

async function executeServe(path, port) {
  let args = ["serve"];
  let args$1 = port !== undefined ? args.concat([
      "--port",
      port.toString()
    ]) : args;
  return await $$Deno.Command.run("marmot", args$1, path);
}

async function executeWatch(path) {
  return await $$Deno.Command.run("marmot", ["watch"], path);
}

async function executeVersion() {
  return await $$Deno.Command.run("marmot", ["--version"], undefined);
}

let name = "Marmot";

let language = "Crystal";

let description = "Fast static site generator written in Crystal";

export {
  name,
  language,
  description,
  state,
  connect,
  disconnect,
  isConnected,
  makeSchema,
  makeProp,
  tools,
  executeInit,
  executeBuild,
  executeServe,
  executeWatch,
  executeVersion,
}
/* tools Not a pure module */
