// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Deno from "../bindings/Deno.res.js";

let state = {
  connected: false,
  projectPath: undefined
};

async function connect() {
  try {
    let result = await $$Deno.Command.run("mdbook", ["--version"], undefined);
    state.connected = result.success;
    return result.success;
  } catch (exn) {
    state.connected = false;
    return false;
  }
}

async function disconnect() {
  state.connected = false;
}

function isConnected() {
  return state.connected;
}

function makeSchema(props, required) {
  let schema = {};
  schema["type"] = "object";
  schema["properties"] = props;
  if (required.length !== 0) {
    schema["required"] = required.map(prim => prim);
  }
  return schema;
}

function makeProp(typeName, desc) {
  return Object.fromEntries([
    [
      "type",
      typeName
    ],
    [
      "description",
      desc
    ]
  ]);
}

let props = {};

let props$1 = {};

let props$2 = {};

let props$3 = {};

let props$4 = {};

let props$5 = {};

let tools = [
  {
    name: "mdbook_init",
    description: "Initialize a new mdBook",
    inputSchema: (props["path"] = makeProp("string", "Path for the new book"), props["title"] = makeProp("string", "Book title"), props["theme"] = makeProp("boolean", "Copy default theme"), makeSchema(props, []))
  },
  {
    name: "mdbook_build",
    description: "Build the mdBook",
    inputSchema: (props$1["path"] = makeProp("string", "Path to book root"), props$1["dest"] = makeProp("string", "Output directory"), props$1["open"] = makeProp("boolean", "Open in browser after build"), makeSchema(props$1, []))
  },
  {
    name: "mdbook_serve",
    description: "Start mdBook development server",
    inputSchema: (props$2["path"] = makeProp("string", "Path to book root"), props$2["port"] = makeProp("number", "Port number (default: 3000)"), props$2["hostname"] = makeProp("string", "Hostname to bind to"), props$2["open"] = makeProp("boolean", "Open in browser"), makeSchema(props$2, []))
  },
  {
    name: "mdbook_watch",
    description: "Watch for changes and rebuild",
    inputSchema: (props$3["path"] = makeProp("string", "Path to book root"), props$3["dest"] = makeProp("string", "Output directory"), makeSchema(props$3, []))
  },
  {
    name: "mdbook_clean",
    description: "Clean the build directory",
    inputSchema: (props$4["path"] = makeProp("string", "Path to book root"), makeSchema(props$4, []))
  },
  {
    name: "mdbook_test",
    description: "Test Rust code samples in the book",
    inputSchema: (props$5["path"] = makeProp("string", "Path to book root"), props$5["chapter"] = makeProp("string", "Specific chapter to test"), makeSchema(props$5, []))
  },
  {
    name: "mdbook_version",
    description: "Get mdBook version",
    inputSchema: makeSchema({}, [])
  }
];

async function executeInit(path, title, theme) {
  let args = ["init"];
  let args$1 = path !== undefined ? args.concat([path]) : args;
  let args$2 = title !== undefined ? args$1.concat([
      "--title",
      title
    ]) : args$1;
  let args$3 = theme !== undefined && theme ? args$2.concat(["--theme"]) : args$2;
  return await $$Deno.Command.run("mdbook", args$3, undefined);
}

async function executeBuild(path, dest, open_) {
  let args = ["build"];
  let args$1 = dest !== undefined ? args.concat([
      "--dest-dir",
      dest
    ]) : args;
  let args$2 = open_ !== undefined && open_ ? args$1.concat(["--open"]) : args$1;
  return await $$Deno.Command.run("mdbook", args$2, path);
}

async function executeServe(path, port, hostname, open_) {
  let args = ["serve"];
  let args$1 = port !== undefined ? args.concat([
      "--port",
      port.toString()
    ]) : args;
  let args$2 = hostname !== undefined ? args$1.concat([
      "--hostname",
      hostname
    ]) : args$1;
  let args$3 = open_ !== undefined && open_ ? args$2.concat(["--open"]) : args$2;
  return await $$Deno.Command.run("mdbook", args$3, path);
}

async function executeWatch(path, dest) {
  let args = ["watch"];
  let args$1 = dest !== undefined ? args.concat([
      "--dest-dir",
      dest
    ]) : args;
  return await $$Deno.Command.run("mdbook", args$1, path);
}

async function executeClean(path) {
  return await $$Deno.Command.run("mdbook", ["clean"], path);
}

async function executeTest(path, chapter) {
  let args = ["test"];
  let args$1 = chapter !== undefined ? args.concat([
      "--chapter",
      chapter
    ]) : args;
  return await $$Deno.Command.run("mdbook", args$1, path);
}

async function executeVersion() {
  return await $$Deno.Command.run("mdbook", ["--version"], undefined);
}

let name = "MdBook";

let language = "Rust";

let description = "Create books from Markdown files using Rust";

export {
  name,
  language,
  description,
  state,
  connect,
  disconnect,
  isConnected,
  makeSchema,
  makeProp,
  tools,
  executeInit,
  executeBuild,
  executeServe,
  executeWatch,
  executeClean,
  executeTest,
  executeVersion,
}
/* tools Not a pure module */
