// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Deno from "../bindings/Deno.res.js";

let state = {
  connected: false,
  projectPath: undefined
};

async function connect() {
  try {
    let result = await $$Deno.Command.run("mix", ["--version"], undefined);
    state.connected = result.success;
    return result.success;
  } catch (exn) {
    state.connected = false;
    return false;
  }
}

async function disconnect() {
  state.connected = false;
}

function isConnected() {
  return state.connected;
}

function makeSchema(props, required) {
  let schema = {};
  schema["type"] = "object";
  schema["properties"] = props;
  if (required.length !== 0) {
    schema["required"] = required.map(prim => prim);
  }
  return schema;
}

function makeProp(typeName, desc) {
  return Object.fromEntries([
    [
      "type",
      typeName
    ],
    [
      "description",
      desc
    ]
  ]);
}

let props = {};

let props$1 = {};

let props$2 = {};

let tools = [
  {
    name: "nimble_publisher_init",
    description: "Initialize a new Phoenix project with NimblePublisher",
    inputSchema: (props["name"] = makeProp("string", "Project name"), props["path"] = makeProp("string", "Path for the project"), makeSchema(props, ["name"]))
  },
  {
    name: "nimble_publisher_build",
    description: "Compile the Phoenix project",
    inputSchema: (props$1["path"] = makeProp("string", "Path to project root"), makeSchema(props$1, []))
  },
  {
    name: "nimble_publisher_server",
    description: "Start Phoenix development server",
    inputSchema: (props$2["path"] = makeProp("string", "Path to project root"), props$2["port"] = makeProp("number", "Port number (default: 4000)"), makeSchema(props$2, []))
  },
  {
    name: "nimble_publisher_version",
    description: "Get Mix/Elixir version",
    inputSchema: makeSchema({}, [])
  }
];

async function executeInit(name, path) {
  return await $$Deno.Command.run("mix", [
    "phx.new",
    name
  ], path);
}

async function executeBuild(path) {
  return await $$Deno.Command.run("mix", ["compile"], path);
}

async function executeServer(path, port) {
  let args = ["phx.server"];
  return await $$Deno.Command.run("mix", args, path);
}

async function executeVersion() {
  return await $$Deno.Command.run("mix", ["--version"], undefined);
}

let name = "NimblePublisher";

let language = "Elixir";

let description = "Markdown-based publishing library for Elixir/Phoenix";

export {
  name,
  language,
  description,
  state,
  connect,
  disconnect,
  isConnected,
  makeSchema,
  makeProp,
  tools,
  executeInit,
  executeBuild,
  executeServer,
  executeVersion,
}
/* tools Not a pure module */
