// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Deno from "../bindings/Deno.res.js";

let state = {
  connected: false,
  projectPath: undefined
};

async function connect() {
  try {
    let result = await $$Deno.Command.run("nim", ["--version"], undefined);
    state.connected = result.success;
    return result.success;
  } catch (exn) {
    state.connected = false;
    return false;
  }
}

async function disconnect() {
  state.connected = false;
}

function isConnected() {
  return state.connected;
}

function makeSchema(props, required) {
  let schema = {};
  schema["type"] = "object";
  schema["properties"] = props;
  if (required.length !== 0) {
    schema["required"] = required.map(prim => prim);
  }
  return schema;
}

function makeProp(typeName, desc) {
  return Object.fromEntries([
    [
      "type",
      typeName
    ],
    [
      "description",
      desc
    ]
  ]);
}

let props = {};

let props$1 = {};

let props$2 = {};

let props$3 = {};

let tools = [
  {
    name: "nimrod_init",
    description: "Initialize a new Nimrod site",
    inputSchema: (props["path"] = makeProp("string", "Path for the new site"), props["template"] = makeProp("string", "Template to use"), makeSchema(props, ["path"]))
  },
  {
    name: "nimrod_build",
    description: "Build the Nimrod site",
    inputSchema: (props$1["path"] = makeProp("string", "Path to site root"), props$1["release"] = makeProp("boolean", "Build in release mode"), makeSchema(props$1, []))
  },
  {
    name: "nimrod_serve",
    description: "Start Nimrod development server",
    inputSchema: (props$2["path"] = makeProp("string", "Path to site root"), props$2["port"] = makeProp("number", "Port number"), makeSchema(props$2, []))
  },
  {
    name: "nimrod_clean",
    description: "Clean build artifacts",
    inputSchema: (props$3["path"] = makeProp("string", "Path to site root"), makeSchema(props$3, []))
  },
  {
    name: "nimrod_version",
    description: "Get Nim version",
    inputSchema: makeSchema({}, [])
  }
];

async function executeInit(path, template) {
  let args = [
    "init",
    path
  ];
  let args$1 = template !== undefined ? args.concat([
      "--template",
      template
    ]) : args;
  return await $$Deno.Command.run("nimrod", args$1, undefined);
}

async function executeBuild(path, release) {
  let args = ["build"];
  let args$1 = release !== undefined && release ? args.concat(["--release"]) : args;
  return await $$Deno.Command.run("nimrod", args$1, path);
}

async function executeServe(path, port) {
  let args = ["serve"];
  let args$1 = port !== undefined ? args.concat([
      "--port",
      port.toString()
    ]) : args;
  return await $$Deno.Command.run("nimrod", args$1, path);
}

async function executeClean(path) {
  return await $$Deno.Command.run("nimrod", ["clean"], path);
}

async function executeVersion() {
  return await $$Deno.Command.run("nim", ["--version"], undefined);
}

let name = "Nimrod";

let language = "Nim";

let description = "Static site generator written in Nim";

export {
  name,
  language,
  description,
  state,
  connect,
  disconnect,
  isConnected,
  makeSchema,
  makeProp,
  tools,
  executeInit,
  executeBuild,
  executeServe,
  executeClean,
  executeVersion,
}
/* tools Not a pure module */
