// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Deno from "../bindings/Deno.res.js";

let state = {
  connected: false,
  projectPath: undefined
};

async function connect() {
  try {
    let result = await $$Deno.Command.run("orchid", ["--version"], undefined);
    state.connected = result.success;
    return result.success;
  } catch (exn) {
    state.connected = false;
    return false;
  }
}

async function disconnect() {
  state.connected = false;
}

function isConnected() {
  return state.connected;
}

function makeSchema(props, required) {
  let schema = {};
  schema["type"] = "object";
  schema["properties"] = props;
  if (required.length !== 0) {
    schema["required"] = required.map(prim => prim);
  }
  return schema;
}

function makeProp(typeName, desc) {
  return Object.fromEntries([
    [
      "type",
      typeName
    ],
    [
      "description",
      desc
    ]
  ]);
}

let props = {};

let props$1 = {};

let props$2 = {};

let props$3 = {};

let tools = [
  {
    name: "orchid_init",
    description: "Initialize a new Orchid project",
    inputSchema: (props["path"] = makeProp("string", "Path for the new project"), props["theme"] = makeProp("string", "Theme to use (Editorial, Copper, etc.)"), makeSchema(props, []))
  },
  {
    name: "orchid_build",
    description: "Build the Orchid site",
    inputSchema: (props$1["path"] = makeProp("string", "Path to project root"), props$1["environment"] = makeProp("string", "Build environment (debug, production)"), makeSchema(props$1, []))
  },
  {
    name: "orchid_serve",
    description: "Start Orchid development server",
    inputSchema: (props$2["path"] = makeProp("string", "Path to project root"), props$2["port"] = makeProp("number", "Port number (default: 8080)"), makeSchema(props$2, []))
  },
  {
    name: "orchid_deploy",
    description: "Deploy the Orchid site",
    inputSchema: (props$3["path"] = makeProp("string", "Path to project root"), props$3["destination"] = makeProp("string", "Deploy destination"), makeSchema(props$3, []))
  },
  {
    name: "orchid_version",
    description: "Get Orchid version",
    inputSchema: makeSchema({}, [])
  }
];

async function executeInit(path, theme) {
  let args = ["init"];
  let args$1 = path !== undefined ? args.concat([path]) : args;
  let args$2 = theme !== undefined ? args$1.concat([
      "--theme",
      theme
    ]) : args$1;
  return await $$Deno.Command.run("orchid", args$2, undefined);
}

async function executeBuild(path, environment) {
  let args = ["build"];
  let args$1 = environment !== undefined ? args.concat([
      "--environment",
      environment
    ]) : args;
  return await $$Deno.Command.run("orchid", args$1, path);
}

async function executeServe(path, port) {
  let args = ["serve"];
  let args$1 = port !== undefined ? args.concat([
      "--port",
      port.toString()
    ]) : args;
  return await $$Deno.Command.run("orchid", args$1, path);
}

async function executeDeploy(path, destination) {
  let args = ["deploy"];
  let args$1 = destination !== undefined ? args.concat([
      "--destination",
      destination
    ]) : args;
  return await $$Deno.Command.run("orchid", args$1, path);
}

async function executeVersion() {
  return await $$Deno.Command.run("orchid", ["--version"], undefined);
}

let name = "Orchid";

let language = "Kotlin";

let description = "Powerful static site generator in Kotlin with plugin system";

export {
  name,
  language,
  description,
  state,
  connect,
  disconnect,
  isConnected,
  makeSchema,
  makeProp,
  tools,
  executeInit,
  executeBuild,
  executeServe,
  executeDeploy,
  executeVersion,
}
/* tools Not a pure module */
