// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Deno from "../bindings/Deno.res.js";

let state = {
  connected: false,
  projectPath: undefined
};

async function connect() {
  try {
    let result = await $$Deno.Command.run("boot", ["--version"], undefined);
    state.connected = result.success;
    return result.success;
  } catch (exn) {
    state.connected = false;
    return false;
  }
}

async function disconnect() {
  state.connected = false;
}

function isConnected() {
  return state.connected;
}

function makeSchema(props, required) {
  let schema = {};
  schema["type"] = "object";
  schema["properties"] = props;
  if (required.length !== 0) {
    schema["required"] = required.map(prim => prim);
  }
  return schema;
}

function makeProp(typeName, desc) {
  return Object.fromEntries([
    [
      "type",
      typeName
    ],
    [
      "description",
      desc
    ]
  ]);
}

let props = {};

let props$1 = {};

let props$2 = {};

let tools = [
  {
    name: "perun_init",
    description: "Initialize a new Perun project",
    inputSchema: (props["path"] = makeProp("string", "Path for the new project"), makeSchema(props, ["path"]))
  },
  {
    name: "perun_build",
    description: "Build the Perun site",
    inputSchema: (props$1["path"] = makeProp("string", "Path to project root"), props$1["target"] = makeProp("string", "Build target"), makeSchema(props$1, []))
  },
  {
    name: "perun_dev",
    description: "Start development mode with watch",
    inputSchema: (props$2["path"] = makeProp("string", "Path to project root"), props$2["port"] = makeProp("number", "Port number"), makeSchema(props$2, []))
  },
  {
    name: "perun_version",
    description: "Get Boot version",
    inputSchema: makeSchema({}, [])
  }
];

async function executeInit(path) {
  return await $$Deno.Command.run("boot", [
    "new",
    "perun",
    path
  ], undefined);
}

async function executeBuild(path, target) {
  let args = target !== undefined ? [target] : ["build"];
  return await $$Deno.Command.run("boot", args, path);
}

async function executeDev(path, port) {
  let args = ["dev"];
  let args$1 = port !== undefined ? args.concat([
      "-p",
      port.toString()
    ]) : args;
  return await $$Deno.Command.run("boot", args$1, path);
}

async function executeVersion() {
  return await $$Deno.Command.run("boot", ["--version"], undefined);
}

let name = "Perun";

let language = "Clojure";

let description = "Composable static site generator using Boot build tool";

export {
  name,
  language,
  description,
  state,
  connect,
  disconnect,
  isConnected,
  makeSchema,
  makeProp,
  tools,
  executeInit,
  executeBuild,
  executeDev,
  executeVersion,
}
/* tools Not a pure module */
