// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Deno from "../bindings/Deno.res.js";

let state = {
  connected: false,
  projectPath: undefined
};

async function connect() {
  try {
    let result = await $$Deno.Command.run("raco", [
      "pollen",
      "version"
    ], undefined);
    state.connected = result.success;
    return result.success;
  } catch (exn) {
    state.connected = false;
    return false;
  }
}

async function disconnect() {
  state.connected = false;
}

function isConnected() {
  return state.connected;
}

function makeSchema(props, required) {
  let schema = {};
  schema["type"] = "object";
  schema["properties"] = props;
  if (required.length !== 0) {
    schema["required"] = required.map(prim => prim);
  }
  return schema;
}

function makeProp(typeName, desc) {
  return Object.fromEntries([
    [
      "type",
      typeName
    ],
    [
      "description",
      desc
    ]
  ]);
}

let props = {};

let props$1 = {};

let props$2 = {};

let props$3 = {};

let tools = [
  {
    name: "pollen_start",
    description: "Start Pollen project server",
    inputSchema: (props["path"] = makeProp("string", "Path to project root"), props["port"] = makeProp("number", "Port number (default: 8080)"), makeSchema(props, []))
  },
  {
    name: "pollen_render",
    description: "Render Pollen source files",
    inputSchema: (props$1["path"] = makeProp("string", "Path to project root"), props$1["parallel"] = makeProp("boolean", "Render in parallel"), makeSchema(props$1, []))
  },
  {
    name: "pollen_publish",
    description: "Publish rendered files to output directory",
    inputSchema: (props$2["path"] = makeProp("string", "Path to project root"), props$2["output"] = makeProp("string", "Output directory"), makeSchema(props$2, []))
  },
  {
    name: "pollen_reset",
    description: "Reset Pollen cache",
    inputSchema: (props$3["path"] = makeProp("string", "Path to project root"), makeSchema(props$3, []))
  },
  {
    name: "pollen_version",
    description: "Get Pollen version",
    inputSchema: makeSchema({}, [])
  }
];

async function executeStart(path, port) {
  let args = [
    "pollen",
    "start"
  ];
  let args$1 = port !== undefined ? args.concat([port.toString()]) : args;
  return await $$Deno.Command.run("raco", args$1, path);
}

async function executeRender(path, parallel) {
  let args = [
    "pollen",
    "render"
  ];
  let args$1 = parallel !== undefined && parallel ? args.concat(["-p"]) : args;
  return await $$Deno.Command.run("raco", args$1, path);
}

async function executePublish(path, output) {
  let args = [
    "pollen",
    "publish"
  ];
  let args$1 = output !== undefined ? args.concat([output]) : args;
  return await $$Deno.Command.run("raco", args$1, path);
}

async function executeReset(path) {
  return await $$Deno.Command.run("raco", [
    "pollen",
    "reset"
  ], path);
}

async function executeVersion() {
  return await $$Deno.Command.run("raco", [
    "pollen",
    "version"
  ], undefined);
}

let name = "Pollen";

let language = "Racket";

let description = "Programmable publishing system for making books in Racket";

export {
  name,
  language,
  description,
  state,
  connect,
  disconnect,
  isConnected,
  makeSchema,
  makeProp,
  tools,
  executeStart,
  executeRender,
  executePublish,
  executeReset,
  executeVersion,
}
/* tools Not a pure module */
