// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Deno from "../bindings/Deno.res.js";

let state = {
  connected: false,
  projectPath: undefined
};

async function connect() {
  try {
    let result = await $$Deno.Command.run("publish", ["--version"], undefined);
    state.connected = result.success;
    return result.success;
  } catch (exn) {
    state.connected = false;
    return false;
  }
}

async function disconnect() {
  state.connected = false;
}

function isConnected() {
  return state.connected;
}

function makeSchema(props, required) {
  let schema = {};
  schema["type"] = "object";
  schema["properties"] = props;
  if (required.length !== 0) {
    schema["required"] = required.map(prim => prim);
  }
  return schema;
}

function makeProp(typeName, desc) {
  return Object.fromEntries([
    [
      "type",
      typeName
    ],
    [
      "description",
      desc
    ]
  ]);
}

let props = {};

let props$1 = {};

let props$2 = {};

let props$3 = {};

let tools = [
  {
    name: "publish_new",
    description: "Create a new Publish site",
    inputSchema: (props["path"] = makeProp("string", "Path for the new site"), makeSchema(props, []))
  },
  {
    name: "publish_generate",
    description: "Generate the Publish site",
    inputSchema: (props$1["path"] = makeProp("string", "Path to site root"), makeSchema(props$1, []))
  },
  {
    name: "publish_run",
    description: "Run the Publish development server",
    inputSchema: (props$2["path"] = makeProp("string", "Path to site root"), props$2["port"] = makeProp("number", "Port number (default: 8000)"), makeSchema(props$2, []))
  },
  {
    name: "publish_deploy",
    description: "Deploy the site",
    inputSchema: (props$3["path"] = makeProp("string", "Path to site root"), props$3["method"] = makeProp("string", "Deploy method (git, github)"), makeSchema(props$3, []))
  },
  {
    name: "publish_version",
    description: "Get Publish version",
    inputSchema: makeSchema({}, [])
  }
];

async function executeNew(path) {
  let args = ["new"];
  let args$1 = path !== undefined ? args.concat([path]) : args;
  return await $$Deno.Command.run("publish", args$1, undefined);
}

async function executeGenerate(path) {
  return await $$Deno.Command.run("publish", ["generate"], path);
}

async function executeRun(path, port) {
  let args = ["run"];
  let args$1 = port !== undefined ? args.concat([
      "--port",
      port.toString()
    ]) : args;
  return await $$Deno.Command.run("publish", args$1, path);
}

async function executeDeploy(path, method) {
  let args = ["deploy"];
  let args$1 = method !== undefined ? args.concat(["--" + method]) : args;
  return await $$Deno.Command.run("publish", args$1, path);
}

async function executeVersion() {
  return await $$Deno.Command.run("publish", ["--version"], undefined);
}

let name = "Publish";

let language = "Swift";

let description = "Static site generator for Swift developers";

export {
  name,
  language,
  description,
  state,
  connect,
  disconnect,
  isConnected,
  makeSchema,
  makeProp,
  tools,
  executeNew,
  executeGenerate,
  executeRun,
  executeDeploy,
  executeVersion,
}
/* tools Not a pure module */
