// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Deno from "../bindings/Deno.res.js";

let state = {
  connected: false,
  projectPath: undefined
};

async function connect() {
  try {
    let result = await $$Deno.Command.run("reggae", ["--version"], undefined);
    state.connected = result.success;
    return result.success;
  } catch (exn) {
    state.connected = false;
    return false;
  }
}

async function disconnect() {
  state.connected = false;
}

function isConnected() {
  return state.connected;
}

function makeSchema(props, required) {
  let schema = {};
  schema["type"] = "object";
  schema["properties"] = props;
  if (required.length !== 0) {
    schema["required"] = required.map(prim => prim);
  }
  return schema;
}

function makeProp(typeName, desc) {
  return Object.fromEntries([
    [
      "type",
      typeName
    ],
    [
      "description",
      desc
    ]
  ]);
}

let props = {};

let props$1 = {};

let props$2 = {};

let tools = [
  {
    name: "reggae_init",
    description: "Initialize a Reggae build",
    inputSchema: (props["path"] = makeProp("string", "Path to project root"), props["backend"] = makeProp("string", "Build backend (make, ninja, tup)"), makeSchema(props, []))
  },
  {
    name: "reggae_build",
    description: "Build the project",
    inputSchema: (props$1["path"] = makeProp("string", "Path to project root"), props$1["jobs"] = makeProp("number", "Number of parallel jobs"), makeSchema(props$1, []))
  },
  {
    name: "reggae_clean",
    description: "Clean build artifacts",
    inputSchema: (props$2["path"] = makeProp("string", "Path to project root"), makeSchema(props$2, []))
  },
  {
    name: "reggae_version",
    description: "Get Reggae version",
    inputSchema: makeSchema({}, [])
  }
];

async function executeInit(path, backend) {
  let args = backend !== undefined ? ["--backend=" + backend] : [];
  return await $$Deno.Command.run("reggae", args, path);
}

async function executeBuild(path, jobs) {
  let args = ["build"];
  let args$1 = jobs !== undefined ? args.concat([
      "-j",
      jobs.toString()
    ]) : args;
  return await $$Deno.Command.run("reggae", args$1, path);
}

async function executeClean(path) {
  return await $$Deno.Command.run("reggae", ["clean"], path);
}

async function executeVersion() {
  return await $$Deno.Command.run("reggae", ["--version"], undefined);
}

let name = "Reggae";

let language = "D";

let description = "Build system generator written in D for static sites";

export {
  name,
  language,
  description,
  state,
  connect,
  disconnect,
  isConnected,
  makeSchema,
  makeProp,
  tools,
  executeInit,
  executeBuild,
  executeClean,
  executeVersion,
}
/* tools Not a pure module */
