// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Deno from "../bindings/Deno.res.js";

let state = {
  connected: false,
  projectPath: undefined
};

async function connect() {
  try {
    let result = await $$Deno.Command.run("mill", ["--version"], undefined);
    state.connected = result.success;
    return result.success;
  } catch (exn) {
    state.connected = false;
    return false;
  }
}

async function disconnect() {
  state.connected = false;
}

function isConnected() {
  return state.connected;
}

function makeSchema(props, required) {
  let schema = {};
  schema["type"] = "object";
  schema["properties"] = props;
  if (required.length !== 0) {
    schema["required"] = required.map(prim => prim);
  }
  return schema;
}

function makeProp(typeName, desc) {
  return Object.fromEntries([
    [
      "type",
      typeName
    ],
    [
      "description",
      desc
    ]
  ]);
}

let props = {};

let props$1 = {};

let props$2 = {};

let props$3 = {};

let tools = [
  {
    name: "scalatex_init",
    description: "Initialize a new ScalaTex project",
    inputSchema: (props["name"] = makeProp("string", "Project name"), props["path"] = makeProp("string", "Path for the project"), makeSchema(props, ["name"]))
  },
  {
    name: "scalatex_build",
    description: "Build the ScalaTex document/site",
    inputSchema: (props$1["path"] = makeProp("string", "Path to project root"), props$1["target"] = makeProp("string", "Build target (html, pdf)"), makeSchema(props$1, []))
  },
  {
    name: "scalatex_watch",
    description: "Watch and rebuild on changes",
    inputSchema: (props$2["path"] = makeProp("string", "Path to project root"), makeSchema(props$2, []))
  },
  {
    name: "scalatex_clean",
    description: "Clean build artifacts",
    inputSchema: (props$3["path"] = makeProp("string", "Path to project root"), makeSchema(props$3, []))
  },
  {
    name: "scalatex_version",
    description: "Get Mill/Scala version",
    inputSchema: makeSchema({}, [])
  }
];

async function executeInit(name, path) {
  return await $$Deno.Command.run("mill", [
    "init",
    name
  ], path);
}

async function executeBuild(path, target) {
  let targetName = target !== undefined ? target : "compile";
  return await $$Deno.Command.run("mill", [targetName], path);
}

async function executeWatch(path) {
  return await $$Deno.Command.run("mill", [
    "-w",
    "compile"
  ], path);
}

async function executeClean(path) {
  return await $$Deno.Command.run("mill", ["clean"], path);
}

async function executeVersion() {
  return await $$Deno.Command.run("mill", ["--version"], undefined);
}

let name = "ScalaTex";

let language = "Scala";

let description = "Document and site generation using Scala with LaTeX support";

export {
  name,
  language,
  description,
  state,
  connect,
  disconnect,
  isConnected,
  makeSchema,
  makeProp,
  tools,
  executeInit,
  executeBuild,
  executeWatch,
  executeClean,
  executeVersion,
}
/* tools Not a pure module */
