// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Deno from "../bindings/Deno.res.js";

let state = {
  connected: false,
  projectPath: undefined
};

async function connect() {
  try {
    let result = await $$Deno.Command.run("mix", ["--version"], undefined);
    state.connected = result.success;
    return result.success;
  } catch (exn) {
    state.connected = false;
    return false;
  }
}

async function disconnect() {
  state.connected = false;
}

function isConnected() {
  return state.connected;
}

function makeSchema(props, required) {
  let schema = {};
  schema["type"] = "object";
  schema["properties"] = props;
  if (required.length !== 0) {
    schema["required"] = required.map(prim => prim);
  }
  return schema;
}

function makeProp(typeName, desc) {
  return Object.fromEntries([
    [
      "type",
      typeName
    ],
    [
      "description",
      desc
    ]
  ]);
}

let props = {};

let props$1 = {};

let props$2 = {};

let tools = [
  {
    name: "serum_init",
    description: "Initialize a new Serum project",
    inputSchema: (props["path"] = makeProp("string", "Path for the new project"), makeSchema(props, ["path"]))
  },
  {
    name: "serum_build",
    description: "Build the Serum site",
    inputSchema: (props$1["path"] = makeProp("string", "Path to project root"), props$1["output"] = makeProp("string", "Output directory"), makeSchema(props$1, []))
  },
  {
    name: "serum_server",
    description: "Start Serum development server",
    inputSchema: (props$2["path"] = makeProp("string", "Path to project root"), props$2["port"] = makeProp("number", "Port number (default: 8080)"), makeSchema(props$2, []))
  },
  {
    name: "serum_version",
    description: "Get Serum version",
    inputSchema: makeSchema({}, [])
  }
];

async function executeInit(path) {
  return await $$Deno.Command.run("mix", [
    "serum.new",
    path
  ], undefined);
}

async function executeBuild(path, output) {
  let args = ["serum.build"];
  let args$1 = output !== undefined ? args.concat([
      "--output",
      output
    ]) : args;
  return await $$Deno.Command.run("mix", args$1, path);
}

async function executeServer(path, port) {
  let args = ["serum.server"];
  let args$1 = port !== undefined ? args.concat([
      "--port",
      port.toString()
    ]) : args;
  return await $$Deno.Command.run("mix", args$1, path);
}

async function executeVersion() {
  return await $$Deno.Command.run("mix", [
    "serum",
    "--version"
  ], undefined);
}

let name = "Serum";

let language = "Elixir";

let description = "Simple static website generator written in Elixir";

export {
  name,
  language,
  description,
  state,
  connect,
  disconnect,
  isConnected,
  makeSchema,
  makeProp,
  tools,
  executeInit,
  executeBuild,
  executeServer,
  executeVersion,
}
/* tools Not a pure module */
