// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Deno from "../bindings/Deno.res.js";

let state = {
  connected: false,
  projectPath: undefined
};

async function connect() {
  try {
    let result = await $$Deno.Command.run("julia", ["--version"], undefined);
    state.connected = result.success;
    return result.success;
  } catch (exn) {
    state.connected = false;
    return false;
  }
}

async function disconnect() {
  state.connected = false;
}

function isConnected() {
  return state.connected;
}

function makeSchema(props, required) {
  let schema = {};
  schema["type"] = "object";
  schema["properties"] = props;
  if (required.length !== 0) {
    schema["required"] = required.map(prim => prim);
  }
  return schema;
}

function makeProp(typeName, desc) {
  return Object.fromEntries([
    [
      "type",
      typeName
    ],
    [
      "description",
      desc
    ]
  ]);
}

let props = {};

let props$1 = {};

let props$2 = {};

let tools = [
  {
    name: "staticwebpages_init",
    description: "Initialize a new StaticWebPages project",
    inputSchema: (props["path"] = makeProp("string", "Path for the new project"), props["template"] = makeProp("string", "Template (academic, portfolio)"), makeSchema(props, ["path"]))
  },
  {
    name: "staticwebpages_build",
    description: "Build the static website",
    inputSchema: (props$1["path"] = makeProp("string", "Path to project root"), props$1["output"] = makeProp("string", "Output directory"), makeSchema(props$1, []))
  },
  {
    name: "staticwebpages_serve",
    description: "Start local development server",
    inputSchema: (props$2["path"] = makeProp("string", "Path to project root"), props$2["port"] = makeProp("number", "Port number"), makeSchema(props$2, []))
  },
  {
    name: "staticwebpages_version",
    description: "Get Julia version",
    inputSchema: makeSchema({}, [])
  }
];

async function executeInit(path, template) {
  let templateArg = template !== undefined ? `, template=:` + template : "";
  return await $$Deno.Command.run("julia", [
    "-e",
    `using StaticWebPages; init("` + path + `"` + templateArg + `)`
  ], undefined);
}

async function executeBuild(path, output) {
  let outputArg = output !== undefined ? `, output="` + output + `"` : "";
  let dir = path !== undefined ? `cd("` + path + `"); ` : "";
  return await $$Deno.Command.run("julia", [
    "-e",
    `using StaticWebPages; ` + dir + `build(` + outputArg + `)`
  ], undefined);
}

async function executeServe(path, port) {
  let portArg = port !== undefined ? `, port=` + port.toString() : "";
  let dir = path !== undefined ? `cd("` + path + `"); ` : "";
  return await $$Deno.Command.run("julia", [
    "-e",
    `using StaticWebPages; ` + dir + `serve(` + portArg + `)`
  ], undefined);
}

async function executeVersion() {
  return await $$Deno.Command.run("julia", ["--version"], undefined);
}

let name = "StaticWebPages";

let language = "Julia";

let description = "Static website generator for academics in Julia";

export {
  name,
  language,
  description,
  state,
  connect,
  disconnect,
  isConnected,
  makeSchema,
  makeProp,
  tools,
  executeInit,
  executeBuild,
  executeServe,
  executeVersion,
}
/* tools Not a pure module */
