// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Deno from "../bindings/Deno.res.js";

let state = {
  connected: false,
  projectPath: undefined
};

async function connect() {
  try {
    let result = await $$Deno.Command.run("mix", ["--version"], undefined);
    state.connected = result.success;
    return result.success;
  } catch (exn) {
    state.connected = false;
    return false;
  }
}

async function disconnect() {
  state.connected = false;
}

function isConnected() {
  return state.connected;
}

function makeSchema(props, required) {
  let schema = {};
  schema["type"] = "object";
  schema["properties"] = props;
  if (required.length !== 0) {
    schema["required"] = required.map(prim => prim);
  }
  return schema;
}

function makeProp(typeName, desc) {
  return Object.fromEntries([
    [
      "type",
      typeName
    ],
    [
      "description",
      desc
    ]
  ]);
}

let props = {};

let props$1 = {};

let props$2 = {};

let tools = [
  {
    name: "tableau_init",
    description: "Initialize a new Tableau project",
    inputSchema: (props["name"] = makeProp("string", "Project name"), props["path"] = makeProp("string", "Path for the project"), makeSchema(props, ["name"]))
  },
  {
    name: "tableau_build",
    description: "Build the Tableau site",
    inputSchema: (props$1["path"] = makeProp("string", "Path to project root"), makeSchema(props$1, []))
  },
  {
    name: "tableau_server",
    description: "Start Tableau development server",
    inputSchema: (props$2["path"] = makeProp("string", "Path to project root"), props$2["port"] = makeProp("number", "Port number"), makeSchema(props$2, []))
  },
  {
    name: "tableau_version",
    description: "Get Mix/Elixir version",
    inputSchema: makeSchema({}, [])
  }
];

async function executeInit(name, path) {
  return await $$Deno.Command.run("mix", [
    "tableau.new",
    name
  ], path);
}

async function executeBuild(path) {
  return await $$Deno.Command.run("mix", ["tableau.build"], path);
}

async function executeServer(path, _port) {
  return await $$Deno.Command.run("mix", ["tableau.server"], path);
}

async function executeVersion() {
  return await $$Deno.Command.run("mix", ["--version"], undefined);
}

let name = "Tableau";

let language = "Elixir";

let description = "Static site generator for Elixir with LiveView support";

export {
  name,
  language,
  description,
  state,
  connect,
  disconnect,
  isConnected,
  makeSchema,
  makeProp,
  tools,
  executeInit,
  executeBuild,
  executeServer,
  executeVersion,
}
/* tools Not a pure module */
