// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Deno from "../bindings/Deno.res.js";

let state = {
  connected: false,
  projectPath: undefined
};

async function connect() {
  try {
    await $$Deno.Command.run("tclsh", ["--version"], undefined);
    state.connected = true;
    return true;
  } catch (exn) {
    state.connected = false;
    return false;
  }
}

async function disconnect() {
  state.connected = false;
}

function isConnected() {
  return state.connected;
}

function makeSchema(props, required) {
  let schema = {};
  schema["type"] = "object";
  schema["properties"] = props;
  if (required.length !== 0) {
    schema["required"] = required.map(prim => prim);
  }
  return schema;
}

function makeProp(typeName, desc) {
  return Object.fromEntries([
    [
      "type",
      typeName
    ],
    [
      "description",
      desc
    ]
  ]);
}

let props = {};

let props$1 = {};

let props$2 = {};

let tools = [
  {
    name: "wub_init",
    description: "Initialize a new Wub project",
    inputSchema: (props["path"] = makeProp("string", "Path for the new project"), makeSchema(props, ["path"]))
  },
  {
    name: "wub_serve",
    description: "Start Wub server",
    inputSchema: (props$1["path"] = makeProp("string", "Path to project root"), props$1["port"] = makeProp("number", "Port number (default: 8080)"), makeSchema(props$1, []))
  },
  {
    name: "wub_generate",
    description: "Generate static files",
    inputSchema: (props$2["path"] = makeProp("string", "Path to project root"), props$2["output"] = makeProp("string", "Output directory"), makeSchema(props$2, []))
  },
  {
    name: "wub_version",
    description: "Get Tcl version",
    inputSchema: makeSchema({}, [])
  }
];

async function executeInit(path) {
  return await $$Deno.Command.run("tclsh", [
    "wub.tcl",
    "init",
    path
  ], undefined);
}

async function executeServe(path, port) {
  let args = [
    "wub.tcl",
    "serve"
  ];
  let args$1 = port !== undefined ? args.concat([
      "-port",
      port.toString()
    ]) : args;
  return await $$Deno.Command.run("tclsh", args$1, path);
}

async function executeGenerate(path, output) {
  let args = [
    "wub.tcl",
    "generate"
  ];
  let args$1 = output !== undefined ? args.concat([
      "-output",
      output
    ]) : args;
  return await $$Deno.Command.run("tclsh", args$1, path);
}

async function executeVersion() {
  return await $$Deno.Command.run("tclsh", [
    "-c",
    "puts [info patchlevel]"
  ], undefined);
}

let name = "Wub";

let language = "Tcl";

let description = "Web application framework and static site generator in Tcl";

export {
  name,
  language,
  description,
  state,
  connect,
  disconnect,
  isConnected,
  makeSchema,
  makeProp,
  tools,
  executeInit,
  executeServe,
  executeGenerate,
  executeVersion,
}
/* tools Not a pure module */
