// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Deno from "../bindings/Deno.res.js";

let state = {
  connected: false,
  projectPath: undefined
};

async function connect() {
  try {
    let result = await $$Deno.Command.run("opam", ["--version"], undefined);
    state.connected = result.success;
    return result.success;
  } catch (exn) {
    state.connected = false;
    return false;
  }
}

async function disconnect() {
  state.connected = false;
}

function isConnected() {
  return state.connected;
}

function makeSchema(props, required) {
  let schema = {};
  schema["type"] = "object";
  schema["properties"] = props;
  if (required.length !== 0) {
    schema["required"] = required.map(prim => prim);
  }
  return schema;
}

function makeProp(typeName, desc) {
  return Object.fromEntries([
    [
      "type",
      typeName
    ],
    [
      "description",
      desc
    ]
  ]);
}

let props = {};

let props$1 = {};

let props$2 = {};

let props$3 = {};

let tools = [
  {
    name: "yocaml_init",
    description: "Initialize a new YOCaml project",
    inputSchema: (props["name"] = makeProp("string", "Project name"), props["path"] = makeProp("string", "Path for the project"), makeSchema(props, ["name"]))
  },
  {
    name: "yocaml_build",
    description: "Build the YOCaml site",
    inputSchema: (props$1["path"] = makeProp("string", "Path to project root"), makeSchema(props$1, []))
  },
  {
    name: "yocaml_watch",
    description: "Watch and rebuild on changes",
    inputSchema: (props$2["path"] = makeProp("string", "Path to project root"), makeSchema(props$2, []))
  },
  {
    name: "yocaml_clean",
    description: "Clean build artifacts",
    inputSchema: (props$3["path"] = makeProp("string", "Path to project root"), makeSchema(props$3, []))
  },
  {
    name: "yocaml_version",
    description: "Get opam/OCaml version",
    inputSchema: makeSchema({}, [])
  }
];

async function executeInit(name, path) {
  return await $$Deno.Command.run("dune", [
    "init",
    "project",
    name
  ], path);
}

async function executeBuild(path) {
  return await $$Deno.Command.run("dune", ["build"], path);
}

async function executeWatch(path) {
  return await $$Deno.Command.run("dune", [
    "build",
    "--watch"
  ], path);
}

async function executeClean(path) {
  return await $$Deno.Command.run("dune", ["clean"], path);
}

async function executeVersion() {
  return await $$Deno.Command.run("opam", ["--version"], undefined);
}

let name = "YOCaml";

let language = "OCaml";

let description = "Static site generator in OCaml with composable build rules";

export {
  name,
  language,
  description,
  state,
  connect,
  disconnect,
  isConnected,
  makeSchema,
  makeProp,
  tools,
  executeInit,
  executeBuild,
  executeWatch,
  executeClean,
  executeVersion,
}
/* tools Not a pure module */
