// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Deno from "../bindings/Deno.res.js";

let state = {
  connected: false,
  projectPath: undefined
};

async function connect() {
  try {
    let result = await $$Deno.Command.run("zola", ["--version"], undefined);
    state.connected = result.success;
    return result.success;
  } catch (exn) {
    state.connected = false;
    return false;
  }
}

async function disconnect() {
  state.connected = false;
}

function isConnected() {
  return state.connected;
}

function makeSchema(props, required) {
  let schema = {};
  schema["type"] = "object";
  schema["properties"] = props;
  if (required.length !== 0) {
    schema["required"] = required.map(prim => prim);
  }
  return schema;
}

function makeProp(typeName, desc) {
  return Object.fromEntries([
    [
      "type",
      typeName
    ],
    [
      "description",
      desc
    ]
  ]);
}

let props = {};

let props$1 = {};

let props$2 = {};

let props$3 = {};

let tools = [
  {
    name: "zola_init",
    description: "Initialize a new Zola site",
    inputSchema: (props["path"] = makeProp("string", "Path for the new site"), props["force"] = makeProp("boolean", "Overwrite existing directory"), makeSchema(props, ["path"]))
  },
  {
    name: "zola_build",
    description: "Build the Zola site",
    inputSchema: (props$1["path"] = makeProp("string", "Path to site root"), props$1["baseUrl"] = makeProp("string", "Base URL for the site"), props$1["outputDir"] = makeProp("string", "Output directory"), props$1["drafts"] = makeProp("boolean", "Include drafts"), makeSchema(props$1, []))
  },
  {
    name: "zola_serve",
    description: "Start Zola development server",
    inputSchema: (props$2["path"] = makeProp("string", "Path to site root"), props$2["port"] = makeProp("number", "Port number (default: 1111)"), props$2["interface"] = makeProp("string", "Interface to bind to"), props$2["drafts"] = makeProp("boolean", "Include drafts"), props$2["openBrowser"] = makeProp("boolean", "Open browser automatically"), makeSchema(props$2, []))
  },
  {
    name: "zola_check",
    description: "Check the site for errors",
    inputSchema: (props$3["path"] = makeProp("string", "Path to site root"), props$3["drafts"] = makeProp("boolean", "Include drafts"), makeSchema(props$3, []))
  },
  {
    name: "zola_version",
    description: "Get Zola version",
    inputSchema: makeSchema({}, [])
  }
];

async function executeInit(path, force) {
  let args = [
    "init",
    path
  ];
  let args$1 = force !== undefined && force ? args.concat(["--force"]) : args;
  return await $$Deno.Command.run("zola", args$1, undefined);
}

async function executeBuild(path, baseUrl, outputDir, drafts) {
  let args = ["build"];
  let args$1 = baseUrl !== undefined ? args.concat([
      "--base-url",
      baseUrl
    ]) : args;
  let args$2 = outputDir !== undefined ? args$1.concat([
      "--output-dir",
      outputDir
    ]) : args$1;
  let args$3 = drafts !== undefined && drafts ? args$2.concat(["--drafts"]) : args$2;
  return await $$Deno.Command.run("zola", args$3, path);
}

async function executeServe(path, port, iface, drafts, openBrowser) {
  let args = ["serve"];
  let args$1 = port !== undefined ? args.concat([
      "--port",
      port.toString()
    ]) : args;
  let args$2 = iface !== undefined ? args$1.concat([
      "--interface",
      iface
    ]) : args$1;
  let args$3 = drafts !== undefined && drafts ? args$2.concat(["--drafts"]) : args$2;
  let args$4 = openBrowser !== undefined && openBrowser ? args$3.concat(["--open"]) : args$3;
  return await $$Deno.Command.run("zola", args$4, path);
}

async function executeCheck(path, drafts) {
  let args = ["check"];
  let args$1 = drafts !== undefined && drafts ? args.concat(["--drafts"]) : args;
  return await $$Deno.Command.run("zola", args$1, path);
}

async function executeVersion() {
  return await $$Deno.Command.run("zola", ["--version"], undefined);
}

let name = "Zola";

let language = "Rust";

let description = "Fast static site generator written in Rust with built-in Sass compilation and syntax highlighting";

export {
  name,
  language,
  description,
  state,
  connect,
  disconnect,
  isConnected,
  makeSchema,
  makeProp,
  tools,
  executeInit,
  executeBuild,
  executeServe,
  executeCheck,
  executeVersion,
}
/* tools Not a pure module */
