// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Deno from "../bindings/Deno.res.js";

let state = {
  connected: false,
  projectPath: undefined
};

async function connect() {
  try {
    let result = await $$Deno.Command.run("zotonic", ["status"], undefined);
    state.connected = result.success;
    return result.success;
  } catch (exn) {
    state.connected = false;
    return false;
  }
}

async function disconnect() {
  state.connected = false;
}

function isConnected() {
  return state.connected;
}

function makeSchema(props, required) {
  let schema = {};
  schema["type"] = "object";
  schema["properties"] = props;
  if (required.length !== 0) {
    schema["required"] = required.map(prim => prim);
  }
  return schema;
}

function makeProp(typeName, desc) {
  return Object.fromEntries([
    [
      "type",
      typeName
    ],
    [
      "description",
      desc
    ]
  ]);
}

let props = {};

let props$1 = {};

let props$2 = {};

let props$3 = {};

let props$4 = {};

let props$5 = {};

let tools = [
  {
    name: "zotonic_siteadd",
    description: "Add a new Zotonic site",
    inputSchema: (props["name"] = makeProp("string", "Site name"), props["hostname"] = makeProp("string", "Site hostname"), makeSchema(props, ["name"]))
  },
  {
    name: "zotonic_start",
    description: "Start Zotonic",
    inputSchema: (props$1["path"] = makeProp("string", "Path to Zotonic installation"), makeSchema(props$1, []))
  },
  {
    name: "zotonic_stop",
    description: "Stop Zotonic",
    inputSchema: (props$2["path"] = makeProp("string", "Path to Zotonic installation"), makeSchema(props$2, []))
  },
  {
    name: "zotonic_sitestart",
    description: "Start a specific site",
    inputSchema: (props$3["name"] = makeProp("string", "Site name"), makeSchema(props$3, ["name"]))
  },
  {
    name: "zotonic_sitestop",
    description: "Stop a specific site",
    inputSchema: (props$4["name"] = makeProp("string", "Site name"), makeSchema(props$4, ["name"]))
  },
  {
    name: "zotonic_compile",
    description: "Compile Zotonic",
    inputSchema: (props$5["path"] = makeProp("string", "Path to Zotonic installation"), makeSchema(props$5, []))
  },
  {
    name: "zotonic_version",
    description: "Get Zotonic version",
    inputSchema: makeSchema({}, [])
  }
];

async function executeSiteadd(name, hostname) {
  let args = [
    "siteadd",
    name
  ];
  let args$1 = hostname !== undefined ? args.concat([
      "-h",
      hostname
    ]) : args;
  return await $$Deno.Command.run("zotonic", args$1, undefined);
}

async function executeStart(path) {
  return await $$Deno.Command.run("zotonic", ["start"], path);
}

async function executeStop(path) {
  return await $$Deno.Command.run("zotonic", ["stop"], path);
}

async function executeSitestart(name) {
  return await $$Deno.Command.run("zotonic", [
    "sitestart",
    name
  ], undefined);
}

async function executeSitestop(name) {
  return await $$Deno.Command.run("zotonic", [
    "sitestop",
    name
  ], undefined);
}

async function executeCompile(path) {
  return await $$Deno.Command.run("zotonic", ["compile"], path);
}

async function executeVersion() {
  return await $$Deno.Command.run("zotonic", ["status"], undefined);
}

let name = "Zotonic";

let language = "Erlang";

let description = "Content management system and web framework in Erlang";

export {
  name,
  language,
  description,
  state,
  connect,
  disconnect,
  isConnected,
  makeSchema,
  makeProp,
  tools,
  executeSiteadd,
  executeStart,
  executeStop,
  executeSitestart,
  executeSitestop,
  executeCompile,
  executeVersion,
}
/* tools Not a pure module */
