// Generated by ReScript, PLEASE EDIT WITH CARE


let standardTools = [
  "init",
  "build",
  "serve",
  "clean",
  "version",
  "new_post",
  "new_page",
  "check",
  "deploy"
];

export {
  standardTools,
}
/* No side effect */
