// Generated by ReScript, PLEASE EDIT WITH CARE


let allowedCommands = [
  "init",
  "new",
  "create",
  "build",
  "serve",
  "watch",
  "deploy",
  "check",
  "clean",
  "version",
  "help",
  "generate",
  "preview",
  "publish",
  "render"
];

function sanitizeArg(arg) {
  return arg.replace(/[;&|`$(){}\\[\\]<>]/g, "");
}

function getBinary(ssg) {
  switch (ssg) {
    case "Zola" :
      return "zola";
    case "Cobalt" :
      return "cobalt";
    case "MdBook" :
      return "mdbook";
    case "Serum" :
    case "NimblePublisher" :
    case "Tableau" :
      return "mix";
    case "Hakyll" :
      return "stack";
    case "Ema" :
      return "ema";
    case "YOCaml" :
      return "yocaml";
    case "Fornax" :
      return "fornax";
    case "Publish" :
      return "publish";
    case "Coleslaw" :
      return "coleslaw";
    case "Orchid" :
      return "orchid";
    case "Franklin" :
    case "StaticWebPages" :
    case "Documenter" :
      return "julia";
    case "Cryogen" :
      return "lein";
    case "Perun" :
      return "boot";
    case "Babashka" :
      return "bb";
    case "Laika" :
      return "laika";
    case "ScalaTex" :
      return "mill";
    case "Zotonic" :
      return "zotonic";
    case "Pollen" :
    case "Frog" :
      return "raco";
    case "Reggae" :
      return "reggae";
    case "Wub" :
      return "wub";
    case "Marmot" :
      return "marmot";
    case "Nimrod" :
      return "nimrod";
    case "Corral" :
      return "corral";
  }
}

function getLanguage(ssg) {
  switch (ssg) {
    case "Zola" :
    case "Cobalt" :
    case "MdBook" :
      return "Rust";
    case "Serum" :
    case "NimblePublisher" :
    case "Tableau" :
      return "Elixir";
    case "Hakyll" :
    case "Ema" :
      return "Haskell";
    case "YOCaml" :
      return "OCaml";
    case "Fornax" :
      return "F#";
    case "Publish" :
      return "Swift";
    case "Coleslaw" :
      return "Common Lisp";
    case "Orchid" :
      return "Kotlin";
    case "Franklin" :
    case "StaticWebPages" :
    case "Documenter" :
      return "Julia";
    case "Laika" :
    case "ScalaTex" :
      return "Scala";
    case "Zotonic" :
      return "Erlang";
    case "Pollen" :
    case "Frog" :
      return "Racket";
    case "Reggae" :
      return "D";
    case "Wub" :
      return "Tcl";
    case "Marmot" :
      return "Crystal";
    case "Nimrod" :
      return "Nim";
    case "Corral" :
      return "Pony";
    default:
      return "Clojure";
  }
}

export {
  allowedCommands,
  sanitizeArg,
  getBinary,
  getLanguage,
}
/* No side effect */
