// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Server from "./Server.res.js";
import * as Stdlib_Int from "@rescript/runtime/lib/es6/Stdlib_Int.js";
import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as McpJs from "@modelcontextprotocol/sdk/server/mcp.js";
import * as StdioJs from "@modelcontextprotocol/sdk/server/stdio.js";

function createServer(adapters) {
  let server = new McpJs.McpServer({
    name: "polyglot-ssg-mcp",
    version: Server.packageVersion,
    description: "Unified MCP server for 29 static site generators across 20 languages"
  });
  let emptySchema = {};
  emptySchema["type"] = "object";
  emptySchema["properties"] = {};
  server.tool("ssg_list", "List all available SSG adapters with their languages and connection status", emptySchema, async _params => {
    let handler = Server.ssgListTool(adapters);
    return await handler();
  });
  server.tool("ssg_detect", "Auto-detect which SSGs are installed on the system", emptySchema, async _params => {
    let handler = Server.ssgDetectTool(adapters);
    return await handler();
  });
  let helpSchema = {};
  helpSchema["type"] = "object";
  let helpProps = {};
  let ssgProp = {};
  ssgProp["type"] = "string";
  ssgProp["description"] = "SSG name (e.g., 'zola', 'hakyll', 'franklin')";
  helpProps["ssg"] = ssgProp;
  helpSchema["properties"] = helpProps;
  helpSchema["required"] = ["ssg"];
  server.tool("ssg_help", "Get help for a specific SSG", helpSchema, async params => {
    let handler = Server.ssgHelpTool(adapters);
    return await handler(params);
  });
  server.tool("ssg_version", "Get version information for polyglot-ssg-mcp", emptySchema, async _params => {
    let handler = Server.ssgVersionTool(adapters);
    return await handler();
  });
  adapters.forEach(adapter => {
    adapter.tools.forEach(t => {
      let obj = Stdlib_JSON.Decode.object(t.inputSchema);
      let schemaProps;
      if (obj !== undefined) {
        let props = obj["properties"];
        if (props !== undefined) {
          let p = Stdlib_JSON.Decode.object(props);
          schemaProps = p !== undefined ? p : ({});
        } else {
          schemaProps = {};
        }
      } else {
        schemaProps = {};
      }
      server.tool(t.name, t.description, schemaProps, async params => await Server.executeAdapterTool(adapter, t, params));
    });
  });
  return server;
}

async function startStdioMode(server, adapters) {
  Server.logStartup("Stdio", adapters);
  let transport = new StdioJs.StdioServerTransport();
  return await server.connect(transport);
}

async function startHttpMode(adapters) {
  let p = Deno.env.get("PORT");
  let port;
  if (p !== undefined) {
    let n = Stdlib_Int.fromString(p, undefined);
    port = n !== undefined ? n : 8000;
  } else {
    port = 8000;
  }
  let h = Deno.env.get("HOST");
  let host = h !== undefined ? h : "0.0.0.0";
  Server.logStartup("Http", adapters);
  console.error("Listening on http://" + host + ":" + port.toString() + "/mcp");
  let allTools = [];
  let metaTools = [
    [
      "ssg_list",
      "List all available SSG adapters with their languages and connection status"
    ],
    [
      "ssg_detect",
      "Auto-detect which SSGs are installed"
    ],
    [
      "ssg_help",
      "Get help for a specific SSG"
    ],
    [
      "ssg_version",
      "Get version information"
    ]
  ];
  metaTools.forEach(param => {
    let t = {};
    t["name"] = param[0];
    t["description"] = param[1];
    allTools.push(t);
  });
  adapters.forEach(adapter => {
    adapter.tools.forEach(t => {
      let toolInfo = {};
      toolInfo["name"] = t.name;
      toolInfo["description"] = t.description;
      toolInfo["inputSchema"] = t.inputSchema;
      allTools.push(toolInfo);
    });
  });
  let languageCount = Server.getUniqueLanguages(adapters).length;
  let handler = async request => {
    let url = new URL(request.url);
    if (url.pathname === "/health") {
      let health = {};
      health["status"] = "ok";
      health["version"] = Server.packageVersion;
      health["ssgs"] = adapters.length;
      health["languages"] = languageCount;
      return Response.json(health, {
        status: 200
      });
    }
    if (url.pathname === "/" || url.pathname === "/info") {
      let ssgList = adapters.map(a => {
        let item = {};
        item["name"] = a.name;
        item["language"] = a.language;
        return item;
      });
      let info = {};
      info["name"] = "polyglot-ssg-mcp";
      info["version"] = Server.packageVersion;
      info["protocol"] = "MCP Streamable HTTP";
      info["protocolVersion"] = "2025-06-18";
      info["endpoint"] = "/mcp";
      info["ssgs"] = ssgList;
      info["documentation"] = "https://github.com/hyperpolymath/polyglot-ssg-mcp";
      return Response.json(info, {
        status: 200
      });
    }
    if (url.pathname !== "/mcp") {
      return new Response("Not Found", {
        status: 404
      });
    }
    let error = {};
    error["error"] = "Use POST for MCP requests";
    return Response.json(error, {
      status: 405
    });
  };
  Deno.serve({
    port: port,
    hostname: host
  }, handler);
}

async function main() {
  console.error("polyglot-ssg-mcp starting...");
}

main();

export {
  createServer,
  startStdioMode,
  startHttpMode,
  main,
}
/*  Not a pure module */
