// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mcp from "./bindings/Mcp.res.js";
import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as Stdlib_JsExn from "@rescript/runtime/lib/es6/Stdlib_JsExn.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";
import EmaResJs from "./adapters/Ema.res.js";
import WubResJs from "./adapters/Wub.res.js";
import FrogResJs from "./adapters/Frog.res.js";
import ZolaResJs from "./adapters/Zola.res.js";
import LaikaResJs from "./adapters/Laika.res.js";
import PerunResJs from "./adapters/Perun.res.js";
import SerumResJs from "./adapters/Serum.res.js";
import CobaltResJs from "./adapters/Cobalt.res.js";
import CorralResJs from "./adapters/Corral.res.js";
import FornaxResJs from "./adapters/Fornax.res.js";
import HakyllResJs from "./adapters/Hakyll.res.js";
import MarmotResJs from "./adapters/Marmot.res.js";
import MdbookResJs from "./adapters/Mdbook.res.js";
import NimrodResJs from "./adapters/Nimrod.res.js";
import OrchidResJs from "./adapters/Orchid.res.js";
import PollenResJs from "./adapters/Pollen.res.js";
import ReggaeResJs from "./adapters/Reggae.res.js";
import YocamlResJs from "./adapters/Yocaml.res.js";
import CryogenResJs from "./adapters/Cryogen.res.js";
import PublishResJs from "./adapters/Publish.res.js";
import TableauResJs from "./adapters/Tableau.res.js";
import ZotonicResJs from "./adapters/Zotonic.res.js";
import BabashkaResJs from "./adapters/Babashka.res.js";
import ColeslawResJs from "./adapters/Coleslaw.res.js";
import FranklinResJs from "./adapters/Franklin.res.js";
import ScalatexResJs from "./adapters/Scalatex.res.js";
import DocumenterResJs from "./adapters/Documenter.res.js";
import StaticwebpagesResJs from "./adapters/Staticwebpages.res.js";
import NimblePublisherResJs from "./adapters/NimblePublisher.res.js";

let packageVersion = "1.1.0";

let feedbackUrl = "https://github.com/hyperpolymath/polyglot-ssg-mcp/issues";

let zolaAdapter = ZolaResJs;

let cobaltAdapter = CobaltResJs;

let mdbookAdapter = MdbookResJs;

let serumAdapter = SerumResJs;

let nimblePublisherAdapter = NimblePublisherResJs;

let tableauAdapter = TableauResJs;

let hakyllAdapter = HakyllResJs;

let emaAdapter = EmaResJs;

let yocamlAdapter = YocamlResJs;

let fornaxAdapter = FornaxResJs;

let publishAdapter = PublishResJs;

let coleslawAdapter = ColeslawResJs;

let orchidAdapter = OrchidResJs;

let franklinAdapter = FranklinResJs;

let staticwebpagesAdapter = StaticwebpagesResJs;

let documenterAdapter = DocumenterResJs;

let cryogenAdapter = CryogenResJs;

let perunAdapter = PerunResJs;

let babashkaAdapter = BabashkaResJs;

let laikaAdapter = LaikaResJs;

let scalatexAdapter = ScalatexResJs;

let zotonicAdapter = ZotonicResJs;

let pollenAdapter = PollenResJs;

let frogAdapter = FrogResJs;

let reggaeAdapter = ReggaeResJs;

let wubAdapter = WubResJs;

let marmotAdapter = MarmotResJs;

let nimrodAdapter = NimrodResJs;

let corralAdapter = CorralResJs;

let adapters = [];

function initAdapters() {
  
}

function getUniqueLanguages(adapters) {
  let languages = {};
  adapters.forEach(a => {
    languages[a.language] = true;
  });
  return Object.keys(languages);
}

function groupByLanguage(adapters) {
  let byLang = {};
  adapters.forEach(a => {
    let arr = byLang[a.language];
    let existing = arr !== undefined ? arr : [];
    byLang[a.language] = existing.concat([a]);
  });
  return byLang;
}

function findAdapter(adapters, name) {
  return adapters.find(a => a.name.toLowerCase() === name.toLowerCase());
}

function ssgListTool(adapters) {
  return async () => {
    let list = adapters.map(a => {
      let item = {};
      item["name"] = a.name;
      item["language"] = a.language;
      item["description"] = a.description;
      item["connected"] = a.isConnected();
      item["toolCount"] = a.tools.length;
      return item;
    });
    let byLanguage = groupByLanguage(adapters);
    let byLangJson = {};
    let keys = Object.keys(byLanguage);
    keys.forEach(lang => {
      let arr = byLanguage[lang];
      if (arr !== undefined) {
        byLangJson[lang] = arr.map(a => {
          let item = {};
          item["name"] = a.name;
          item["language"] = a.language;
          return item;
        });
        return;
      }
    });
    let result = {};
    result["total"] = adapters.length;
    result["languages"] = keys.length;
    result["byLanguage"] = byLangJson;
    result["ssgs"] = list;
    return Mcp.makeJsonResult(result);
  };
}

function ssgDetectTool(adapters) {
  return async () => {
    let results = [];
    for (let i = 0, i_finish = adapters.length; i < i_finish; ++i) {
      let a = adapters[i];
      let available;
      try {
        available = await a.connect();
      } catch (exn) {
        available = false;
      }
      let item = {};
      item["name"] = a.name;
      item["language"] = a.language;
      item["available"] = available;
      results.push(item);
    }
    let available$1 = results.filter(r => {
      let obj = Stdlib_JSON.Decode.object(r);
      if (obj === undefined) {
        return false;
      }
      let v = obj["available"];
      if (v === undefined) {
        return false;
      }
      let b = Stdlib_JSON.Decode.bool(v);
      if (b !== undefined) {
        return b;
      } else {
        return false;
      }
    });
    let unavailable = results.filter(r => {
      let obj = Stdlib_JSON.Decode.object(r);
      if (obj === undefined) {
        return true;
      }
      let v = obj["available"];
      if (v === undefined) {
        return true;
      }
      let b = Stdlib_JSON.Decode.bool(v);
      if (b !== undefined) {
        return !b;
      } else {
        return true;
      }
    });
    let summary = available$1.length.toString() + "/" + results.length.toString() + " SSGs available";
    let result = {};
    result["summary"] = summary;
    result["available"] = available$1;
    result["unavailable"] = unavailable;
    result["details"] = results;
    return Mcp.makeJsonResult(result);
  };
}

function ssgHelpTool(adapters) {
  return async params => {
    let obj = Stdlib_JSON.Decode.object(params);
    let ssgName;
    if (obj !== undefined) {
      let v = obj["ssg"];
      ssgName = v !== undefined ? Stdlib_JSON.Decode.string(v) : undefined;
    } else {
      ssgName = undefined;
    }
    if (ssgName === undefined) {
      return Mcp.makeToolResult("Missing required parameter: ssg", true);
    }
    let adapter = findAdapter(adapters, ssgName);
    if (adapter !== undefined) {
      let tools = adapter.tools.map(t => {
        let item = {};
        item["name"] = t.name;
        item["description"] = t.description;
        return item;
      });
      let result = {};
      result["name"] = adapter.name;
      result["language"] = adapter.language;
      result["description"] = adapter.description;
      result["connected"] = adapter.isConnected();
      result["tools"] = tools;
      return Mcp.makeJsonResult(result);
    }
    let availableList = adapters.map(a => "  - " + a.name + " (" + a.language + ")");
    return Mcp.makeToolResult("Unknown SSG: " + ssgName + "\n\nAvailable SSGs:\n" + availableList.join("\n"), true);
  };
}

function ssgVersionTool(adapters) {
  return async () => {
    let languages = getUniqueLanguages(adapters);
    let result = {};
    result["name"] = "polyglot-ssg-mcp";
    result["version"] = packageVersion;
    result["ssgs"] = adapters.length;
    result["languages"] = languages.length;
    result["runtime"] = "Deno";
    result["core"] = "ReScript";
    result["feedback"] = feedbackUrl;
    return Mcp.makeJsonResult(result);
  };
}

function isServerlessEnvironment() {
  if (Stdlib_Option.isSome(Deno.env.get("DENO_DEPLOYMENT_ID")) || Primitive_object.equal(Deno.env.get("MCP_HTTP_MODE"), "true")) {
    return true;
  } else {
    return Deno.args().includes("--http");
  }
}

function detectMode() {
  if (isServerlessEnvironment()) {
    return "Http";
  } else {
    return "Stdio";
  }
}

function logStartup(mode, adapters) {
  let modeStr;
  modeStr = mode === "Stdio" ? "STDIO" : "HTTP";
  let languageCount = getUniqueLanguages(adapters).length;
  console.error("polyglot-ssg-mcp v" + packageVersion + " (" + modeStr + " mode)");
  console.error(adapters.length.toString() + " SSGs across " + languageCount.toString() + " languages");
  console.error("Feedback: " + feedbackUrl);
}

async function executeAdapterTool(adapter, tool, params) {
  try {
    if (adapter.isConnected()) {
      let executeFn = tool.execute;
      if (executeFn !== undefined) {
        return Mcp.makeJsonResult(await executeFn(params));
      } else {
        return Mcp.makeToolResult("Tool execution not implemented", true);
      }
    }
    let connected = await adapter.connect();
    if (!connected) {
      return Mcp.makeToolResult(adapter.name + " is not available. Please install " + adapter.name + " (" + adapter.language + ").", true);
    }
    let executeFn$1 = tool.execute;
    if (executeFn$1 !== undefined) {
      return Mcp.makeJsonResult(await executeFn$1(params));
    } else {
      return Mcp.makeToolResult("Tool execution not implemented", true);
    }
  } catch (raw_e) {
    let e = Primitive_exceptions.internalToException(raw_e);
    if (e.RE_EXN_ID === "JsExn") {
      let m = Stdlib_JsExn.message(e._1);
      let msg = m !== undefined ? m : "Unknown error";
      return Mcp.makeToolResult("Error: " + msg + "\n\nPlease report issues at: " + feedbackUrl, true);
    }
    throw e;
  }
}

export {
  packageVersion,
  feedbackUrl,
  zolaAdapter,
  cobaltAdapter,
  mdbookAdapter,
  serumAdapter,
  nimblePublisherAdapter,
  tableauAdapter,
  hakyllAdapter,
  emaAdapter,
  yocamlAdapter,
  fornaxAdapter,
  publishAdapter,
  coleslawAdapter,
  orchidAdapter,
  franklinAdapter,
  staticwebpagesAdapter,
  documenterAdapter,
  cryogenAdapter,
  perunAdapter,
  babashkaAdapter,
  laikaAdapter,
  scalatexAdapter,
  zotonicAdapter,
  pollenAdapter,
  frogAdapter,
  reggaeAdapter,
  wubAdapter,
  marmotAdapter,
  nimrodAdapter,
  corralAdapter,
  adapters,
  initAdapters,
  getUniqueLanguages,
  groupByLanguage,
  findAdapter,
  ssgListTool,
  ssgDetectTool,
  ssgHelpTool,
  ssgVersionTool,
  isServerlessEnvironment,
  detectMode,
  logStartup,
  executeAdapterTool,
}
/* zolaAdapter Not a pure module */
