// Generated by ReScript, PLEASE EDIT WITH CARE


let TextDecoder = {};

let Env = {};

let Args = {};

let Fs = {};

async function run(binary, args, cwdPath) {
  let cmd = new (Deno.Command)(binary, {
    args: args,
    cwd: cwdPath !== undefined ? cwdPath : Deno.cwd(),
    stdout: "piped",
    stderr: "piped"
  });
  let result = await cmd.output();
  let decoder = new TextDecoder();
  return {
    success: result.success,
    stdout: decoder.decode(result.stdout),
    stderr: decoder.decode(result.stderr),
    code: result.code
  };
}

let Command = {
  run: run
};

export {
  TextDecoder,
  Env,
  Args,
  Fs,
  Command,
}
/* No side effect */
