// Generated by ReScript, PLEASE EDIT WITH CARE


function byteToHex(byte) {
  let hex = "0123456789abcdef";
  let high = hex.charAt(byte / 16 | 0);
  let low = hex.charAt(byte % 16);
  return high + low;
}

function generateSessionId() {
  let array = new Uint8Array(32);
  crypto.getRandomValues(array);
  return array.reduce((acc, byte) => acc + byteToHex(byte), "");
}

export {
  byteToHex,
  generateSessionId,
}
/* No side effect */
