// Generated by ReScript, PLEASE EDIT WITH CARE


function makeTextContent(text) {
  return {
    type: "text",
    text: text
  };
}

function makeToolResult(text, isErrorOpt) {
  let isError = isErrorOpt !== undefined ? isErrorOpt : false;
  return {
    content: [{
        type: "text",
        text: text
      }],
    isError: isError ? true : undefined
  };
}

function makeJsonResult(data) {
  return {
    content: [{
        type: "text",
        text: JSON.stringify(data, undefined, 2)
      }]
  };
}

export {
  makeTextContent,
  makeToolResult,
  makeJsonResult,
}
/* No side effect */
